package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type BigIntSpanSet struct {
	SpanSet
}

// BigIntSpanSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func BigIntSpanSetFromPointer(p unsafe.Pointer) *BigIntSpanSet {
	if p == nil {
		return nil
	}
	v := &BigIntSpanSet{}
	v.ptr = p
	return v
}

// BigIntSpanSetIn is MEOS bigintspanset_in.
func BigIntSpanSetIn(str string) (*SpanSet, error) {
	_r0, _err := functions.BigintspansetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS bigintspanset_out.
func (x *BigIntSpanSet) Out() (string, error) {
	_r0, _err := functions.BigintspansetOut(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Lower is MEOS bigintspanset_lower.
func (x *BigIntSpanSet) Lower() (int64, error) {
	_r0, _err := functions.BigintspansetLower(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS bigintspanset_upper.
func (x *BigIntSpanSet) Upper() (int64, error) {
	_r0, _err := functions.BigintspansetUpper(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Width is MEOS bigintspanset_width.
func (x *BigIntSpanSet) Width(boundspan bool) (int64, error) {
	_r0, _err := functions.BigintspansetWidth(functions.SpanSetFromPointer(x.Pointer()), boundspan)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS bigintspanset_shift_scale.
func (x *BigIntSpanSet) ShiftScale(shift int64, width int64, hasshift bool, haswidth bool) (*SpanSet, error) {
	_r0, _err := functions.BigintspansetShiftScale(functions.SpanSetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS bigintspanset_bins.
func (x *BigIntSpanSet) Bins(vsize int64, vorigin int64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.BigintspansetBins(functions.SpanSetFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
