package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type BigIntSpan struct {
	Span
}

// BigIntSpanFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func BigIntSpanFromPointer(p unsafe.Pointer) *BigIntSpan {
	if p == nil {
		return nil
	}
	v := &BigIntSpan{}
	v.ptr = p
	return v
}

// Expand is MEOS bigintspan_expand.
func (x *BigIntSpan) Expand(value int64) (*Span, error) {
	_r0, _err := functions.BigintspanExpand(functions.SpanFromPointer(x.Pointer()), value)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// BigIntSpanIn is MEOS bigintspan_in.
func BigIntSpanIn(str string) (*Span, error) {
	_r0, _err := functions.BigintspanIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Out is MEOS bigintspan_out.
func (x *BigIntSpan) Out() (string, error) {
	_r0, _err := functions.BigintspanOut(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// BigIntSpanMake is MEOS bigintspan_make.
func BigIntSpanMake(lower int64, upper int64, lower_inc bool, upper_inc bool) (*Span, error) {
	_r0, _err := functions.BigintspanMake(lower, upper, lower_inc, upper_inc)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToIntspan is MEOS bigintspan_to_intspan.
func (x *BigIntSpan) ToIntspan() (*Span, error) {
	_r0, _err := functions.BigintspanToIntspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToFloatspan is MEOS bigintspan_to_floatspan.
func (x *BigIntSpan) ToFloatspan() (*Span, error) {
	_r0, _err := functions.BigintspanToFloatspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS bigintspan_lower.
func (x *BigIntSpan) Lower() (int64, error) {
	_r0, _err := functions.BigintspanLower(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS bigintspan_upper.
func (x *BigIntSpan) Upper() (int64, error) {
	_r0, _err := functions.BigintspanUpper(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Width is MEOS bigintspan_width.
func (x *BigIntSpan) Width() (int64, error) {
	_r0, _err := functions.BigintspanWidth(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS bigintspan_shift_scale.
func (x *BigIntSpan) ShiftScale(shift int64, width int64, hasshift bool, haswidth bool) (*Span, error) {
	_r0, _err := functions.BigintspanShiftScale(functions.SpanFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS bigintspan_bins.
func (x *BigIntSpan) Bins(vsize int64, vorigin int64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.BigintspanBins(functions.SpanFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
