package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type BigIntSet struct {
	Set
}

// BigIntSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func BigIntSetFromPointer(p unsafe.Pointer) *BigIntSet {
	if p == nil {
		return nil
	}
	v := &BigIntSet{}
	v.ptr = p
	return v
}

// BigIntSetIn is MEOS bigintset_in.
func BigIntSetIn(str string) (*Set, error) {
	_r0, _err := functions.BigintsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS bigintset_out.
func (x *BigIntSet) Out() (string, error) {
	_r0, _err := functions.BigintsetOut(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// BigIntSetMake is MEOS bigintset_make.
func BigIntSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.BigintsetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS bigintset_end_value.
func (x *BigIntSet) EndValue() (int64, error) {
	_r0, _err := functions.BigintsetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS bigintset_start_value.
func (x *BigIntSet) StartValue() (int64, error) {
	_r0, _err := functions.BigintsetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueN is MEOS bigintset_value_n.
func (x *BigIntSet) ValueN(n int) (int64, bool, error) {
	_found, _value, _err := functions.BigintsetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS bigintset_values.
func (x *BigIntSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.BigintsetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS bigintset_shift_scale.
func (x *BigIntSet) ShiftScale(shift int64, width int64, hasshift bool, haswidth bool) (*Set, error) {
	_r0, _err := functions.BigintsetShiftScale(functions.SetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
