package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type Box struct {
	handle
}

// BoxFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func BoxFromPointer(p unsafe.Pointer) *Box {
	if p == nil {
		return nil
	}
	v := &Box{}
	v.ptr = p
	return v
}
