package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Cbuffer struct {
	Value
}

// CbufferFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func CbufferFromPointer(p unsafe.Pointer) *Cbuffer {
	if p == nil {
		return nil
	}
	v := &Cbuffer{}
	v.ptr = p
	return v
}

// AsEWKT is MEOS cbuffer_as_ewkt.
func (x *Cbuffer) AsEWKT(maxdd int) (string, error) {
	_r0, _err := functions.CbufferAsEWKT(functions.CbufferFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsHEXWKB is MEOS cbuffer_as_hexwkb.
func (x *Cbuffer) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.CbufferAsHexwkb(functions.CbufferFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsText is MEOS cbuffer_as_text.
func (x *Cbuffer) AsText(maxdd int) (string, error) {
	_r0, _err := functions.CbufferAsText(functions.CbufferFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS cbuffer_as_wkb.
func (x *Cbuffer) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.CbufferAsWKB(functions.CbufferFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// CbufferFromHEXWKB is MEOS cbuffer_from_hexwkb.
func CbufferFromHEXWKB(hexwkb string) (*Cbuffer, error) {
	_r0, _err := functions.CbufferFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// CbufferFromWKB is MEOS cbuffer_from_wkb.
func CbufferFromWKB(wkb unsafe.Pointer, size uint) (*Cbuffer, error) {
	_r0, _err := functions.CbufferFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// CbufferIn is MEOS cbuffer_in.
func CbufferIn(str string) (*Cbuffer, error) {
	_r0, _err := functions.CbufferIn(str)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// Out is MEOS cbuffer_out.
func (x *Cbuffer) Out(maxdd int) (string, error) {
	_r0, _err := functions.CbufferOut(functions.CbufferFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Copy is MEOS cbuffer_copy.
func (x *Cbuffer) Copy() (*Cbuffer, error) {
	_r0, _err := functions.CbufferCopy(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// CbufferMake is MEOS cbuffer_make.
func CbufferMake(point *TRGeometrySeqSet, radius float64) (*Cbuffer, error) {
	_r0, _err := functions.CbufferMake(functions.GeomFromPointer(point.Pointer()), radius)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// ToGeom is MEOS cbuffer_to_geom.
func (x *Cbuffer) ToGeom() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.CbufferToGeom(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS cbuffer_to_stbox.
func (x *Cbuffer) ToStbox() (*STBox, error) {
	_r0, _err := functions.CbufferToSTBOX(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS cbuffer_hash.
func (x *Cbuffer) Hash() (uint32, error) {
	_r0, _err := functions.CbufferHash(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS cbuffer_hash_extended.
func (x *Cbuffer) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.CbufferHashExtended(functions.CbufferFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Point is MEOS cbuffer_point.
func (x *Cbuffer) Point() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.CbufferPoint(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// Radius is MEOS cbuffer_radius.
func (x *Cbuffer) Radius() (float64, error) {
	_r0, _err := functions.CbufferRadius(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Round is MEOS cbuffer_round.
func (x *Cbuffer) Round(maxdd int) (*Cbuffer, error) {
	_r0, _err := functions.CbufferRound(functions.CbufferFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// SetSRID is MEOS cbuffer_set_srid.
func (x *Cbuffer) SetSRID(srid int32) (*Cbuffer, error) {
	_r0, _err := functions.CbufferSetSRID(functions.CbufferFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// SRID is MEOS cbuffer_srid.
func (x *Cbuffer) SRID() (int32, error) {
	_r0, _err := functions.CbufferSRID(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Transform is MEOS cbuffer_transform.
func (x *Cbuffer) Transform(srid int32) (*Cbuffer, error) {
	_r0, _err := functions.CbufferTransform(functions.CbufferFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// TransformPipeline is MEOS cbuffer_transform_pipeline.
func (x *Cbuffer) TransformPipeline(pipelinestr string, srid int32, is_forward bool) (*Cbuffer, error) {
	_r0, _err := functions.CbufferTransformPipeline(functions.CbufferFromPointer(x.Pointer()), pipelinestr, srid, is_forward)
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// TstzspanToStbox is MEOS cbuffer_tstzspan_to_stbox.
func (x *Cbuffer) TstzspanToStbox(s *Span) (*STBox, error) {
	_r0, _err := functions.CbufferTstzspanToSTBOX(functions.CbufferFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// TimestamptzToStbox is MEOS cbuffer_timestamptz_to_stbox.
func (x *Cbuffer) TimestamptzToStbox(t int64) (*STBox, error) {
	_r0, _err := functions.CbufferTimestamptzToSTBOX(functions.CbufferFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS cbuffer_cmp.
func (x *Cbuffer) Cmp(cb2 *Cbuffer) (int, error) {
	_r0, _err := functions.CbufferCmp(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS cbuffer_eq.
func (x *Cbuffer) Eq(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferEq(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS cbuffer_ge.
func (x *Cbuffer) Ge(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferGe(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS cbuffer_gt.
func (x *Cbuffer) Gt(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferGt(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS cbuffer_le.
func (x *Cbuffer) Le(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferLe(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS cbuffer_lt.
func (x *Cbuffer) Lt(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferLt(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS cbuffer_ne.
func (x *Cbuffer) Ne(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferNe(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Nsame is MEOS cbuffer_nsame.
func (x *Cbuffer) Nsame(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferNsame(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Same is MEOS cbuffer_same.
func (x *Cbuffer) Same(cb2 *Cbuffer) (bool, error) {
	_r0, _err := functions.CbufferSame(functions.CbufferFromPointer(x.Pointer()), functions.CbufferFromPointer(cb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ToSet is MEOS cbuffer_to_set.
func (x *Cbuffer) ToSet() (*Set, error) {
	_r0, _err := functions.CbufferToSet(functions.CbufferFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
