package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type CbufferSet struct {
	Set
}

// CbufferSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func CbufferSetFromPointer(p unsafe.Pointer) *CbufferSet {
	if p == nil {
		return nil
	}
	v := &CbufferSet{}
	v.ptr = p
	return v
}

// CbufferSetIn is MEOS cbufferset_in.
func CbufferSetIn(str string) (*Set, error) {
	_r0, _err := functions.CbuffersetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS cbufferset_out.
func (x *CbufferSet) Out(maxdd int) (string, error) {
	_r0, _err := functions.CbuffersetOut(functions.SetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// CbufferSetMake is MEOS cbufferset_make.
func CbufferSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.CbuffersetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS cbufferset_end_value.
func (x *CbufferSet) EndValue() (*Cbuffer, error) {
	_r0, _err := functions.CbuffersetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS cbufferset_start_value.
func (x *CbufferSet) StartValue() (*Cbuffer, error) {
	_r0, _err := functions.CbuffersetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// ValueN is MEOS cbufferset_value_n.
func (x *CbufferSet) ValueN(n int) (*Cbuffer, bool, error) {
	_found, _value, _err := functions.CbuffersetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return CbufferFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS cbufferset_values.
func (x *CbufferSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.CbuffersetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
