package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type Collection struct {
	handle
}

// CollectionFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func CollectionFromPointer(p unsafe.Pointer) *Collection {
	if p == nil {
		return nil
	}
	v := &Collection{}
	v.ptr = p
	return v
}
