package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type DateSet struct {
	Set
}

// DateSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func DateSetFromPointer(p unsafe.Pointer) *DateSet {
	if p == nil {
		return nil
	}
	v := &DateSet{}
	v.ptr = p
	return v
}

// DateSetIn is MEOS dateset_in.
func DateSetIn(str string) (*Set, error) {
	_r0, _err := functions.DatesetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS dateset_out.
func (x *DateSet) Out() (string, error) {
	_r0, _err := functions.DatesetOut(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// DateSetMake is MEOS dateset_make.
func DateSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.DatesetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToTstzset is MEOS dateset_to_tstzset.
func (x *DateSet) ToTstzset() (*Set, error) {
	_r0, _err := functions.DatesetToTstzset(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS dateset_end_value.
func (x *DateSet) EndValue() (int32, error) {
	_r0, _err := functions.DatesetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS dateset_start_value.
func (x *DateSet) StartValue() (int32, error) {
	_r0, _err := functions.DatesetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueN is MEOS dateset_value_n.
func (x *DateSet) ValueN(n int) (int32, bool, error) {
	_found, _value, _err := functions.DatesetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS dateset_values.
func (x *DateSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.DatesetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS dateset_shift_scale.
func (x *DateSet) ShiftScale(shift int, width int, hasshift bool, haswidth bool) (*Set, error) {
	_r0, _err := functions.DatesetShiftScale(functions.SetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
