package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type DateSpan struct {
	Span
}

// DateSpanFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func DateSpanFromPointer(p unsafe.Pointer) *DateSpan {
	if p == nil {
		return nil
	}
	v := &DateSpan{}
	v.ptr = p
	return v
}

// DateSpanIn is MEOS datespan_in.
func DateSpanIn(str string) (*Span, error) {
	_r0, _err := functions.DatespanIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Out is MEOS datespan_out.
func (x *DateSpan) Out() (string, error) {
	_r0, _err := functions.DatespanOut(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// DateSpanMake is MEOS datespan_make.
func DateSpanMake(lower int32, upper int32, lower_inc bool, upper_inc bool) (*Span, error) {
	_r0, _err := functions.DatespanMake(lower, upper, lower_inc, upper_inc)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToTstzspan is MEOS datespan_to_tstzspan.
func (x *DateSpan) ToTstzspan() (*Span, error) {
	_r0, _err := functions.DatespanToTstzspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS datespan_lower.
func (x *DateSpan) Lower() (int32, error) {
	_r0, _err := functions.DatespanLower(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS datespan_upper.
func (x *DateSpan) Upper() (int32, error) {
	_r0, _err := functions.DatespanUpper(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS datespan_shift_scale.
func (x *DateSpan) ShiftScale(shift int, width int, hasshift bool, haswidth bool) (*Span, error) {
	_r0, _err := functions.DatespanShiftScale(functions.SpanFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
