package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type FloatSpan struct {
	Span
}

// FloatSpanFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func FloatSpanFromPointer(p unsafe.Pointer) *FloatSpan {
	if p == nil {
		return nil
	}
	v := &FloatSpan{}
	v.ptr = p
	return v
}

// Expand is MEOS floatspan_expand.
func (x *FloatSpan) Expand(value float64) (*Span, error) {
	_r0, _err := functions.FloatspanExpand(functions.SpanFromPointer(x.Pointer()), value)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// FloatSpanIn is MEOS floatspan_in.
func FloatSpanIn(str string) (*Span, error) {
	_r0, _err := functions.FloatspanIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Out is MEOS floatspan_out.
func (x *FloatSpan) Out(maxdd int) (string, error) {
	_r0, _err := functions.FloatspanOut(functions.SpanFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// FloatSpanMake is MEOS floatspan_make.
func FloatSpanMake(lower float64, upper float64, lower_inc bool, upper_inc bool) (*Span, error) {
	_r0, _err := functions.FloatspanMake(lower, upper, lower_inc, upper_inc)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToIntspan is MEOS floatspan_to_intspan.
func (x *FloatSpan) ToIntspan() (*Span, error) {
	_r0, _err := functions.FloatspanToIntspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToBigintspan is MEOS floatspan_to_bigintspan.
func (x *FloatSpan) ToBigintspan() (*Span, error) {
	_r0, _err := functions.FloatspanToBigintspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS floatspan_lower.
func (x *FloatSpan) Lower() (float64, error) {
	_r0, _err := functions.FloatspanLower(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS floatspan_upper.
func (x *FloatSpan) Upper() (float64, error) {
	_r0, _err := functions.FloatspanUpper(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Width is MEOS floatspan_width.
func (x *FloatSpan) Width() (float64, error) {
	_r0, _err := functions.FloatspanWidth(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Ceil is MEOS floatspan_ceil.
func (x *FloatSpan) Ceil() (*Span, error) {
	_r0, _err := functions.FloatspanCeil(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Degrees is MEOS floatspan_degrees.
func (x *FloatSpan) Degrees(normalize bool) (*Span, error) {
	_r0, _err := functions.FloatspanDegrees(functions.SpanFromPointer(x.Pointer()), normalize)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Floor is MEOS floatspan_floor.
func (x *FloatSpan) Floor() (*Span, error) {
	_r0, _err := functions.FloatspanFloor(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Radians is MEOS floatspan_radians.
func (x *FloatSpan) Radians() (*Span, error) {
	_r0, _err := functions.FloatspanRadians(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Round is MEOS floatspan_round.
func (x *FloatSpan) Round(maxdd int) (*Span, error) {
	_r0, _err := functions.FloatspanRound(functions.SpanFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ShiftScale is MEOS floatspan_shift_scale.
func (x *FloatSpan) ShiftScale(shift float64, width float64, hasshift bool, haswidth bool) (*Span, error) {
	_r0, _err := functions.FloatspanShiftScale(functions.SpanFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS floatspan_bins.
func (x *FloatSpan) Bins(vsize float64, vorigin float64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.FloatspanBins(functions.SpanFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
