package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type FloatSet struct {
	Set
}

// FloatSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func FloatSetFromPointer(p unsafe.Pointer) *FloatSet {
	if p == nil {
		return nil
	}
	v := &FloatSet{}
	v.ptr = p
	return v
}

// FloatSetIn is MEOS floatset_in.
func FloatSetIn(str string) (*Set, error) {
	_r0, _err := functions.FloatsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS floatset_out.
func (x *FloatSet) Out(maxdd int) (string, error) {
	_r0, _err := functions.FloatsetOut(functions.SetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// FloatSetMake is MEOS floatset_make.
func FloatSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.FloatsetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToIntset is MEOS floatset_to_intset.
func (x *FloatSet) ToIntset() (*Set, error) {
	_r0, _err := functions.FloatsetToIntset(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS floatset_end_value.
func (x *FloatSet) EndValue() (float64, error) {
	_r0, _err := functions.FloatsetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS floatset_start_value.
func (x *FloatSet) StartValue() (float64, error) {
	_r0, _err := functions.FloatsetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueN is MEOS floatset_value_n.
func (x *FloatSet) ValueN(n int) (float64, bool, error) {
	_found, _value, _err := functions.FloatsetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS floatset_values.
func (x *FloatSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.FloatsetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Ceil is MEOS floatset_ceil.
func (x *FloatSet) Ceil() (*Set, error) {
	_r0, _err := functions.FloatsetCeil(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Degrees is MEOS floatset_degrees.
func (x *FloatSet) Degrees(normalize bool) (*Set, error) {
	_r0, _err := functions.FloatsetDegrees(functions.SetFromPointer(x.Pointer()), normalize)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Floor is MEOS floatset_floor.
func (x *FloatSet) Floor() (*Set, error) {
	_r0, _err := functions.FloatsetFloor(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Radians is MEOS floatset_radians.
func (x *FloatSet) Radians() (*Set, error) {
	_r0, _err := functions.FloatsetRadians(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ShiftScale is MEOS floatset_shift_scale.
func (x *FloatSet) ShiftScale(shift float64, width float64, hasshift bool, haswidth bool) (*Set, error) {
	_r0, _err := functions.FloatsetShiftScale(functions.SetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
