package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type FloatSpanSet struct {
	SpanSet
}

// FloatSpanSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func FloatSpanSetFromPointer(p unsafe.Pointer) *FloatSpanSet {
	if p == nil {
		return nil
	}
	v := &FloatSpanSet{}
	v.ptr = p
	return v
}

// FloatSpanSetIn is MEOS floatspanset_in.
func FloatSpanSetIn(str string) (*SpanSet, error) {
	_r0, _err := functions.FloatspansetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS floatspanset_out.
func (x *FloatSpanSet) Out(maxdd int) (string, error) {
	_r0, _err := functions.FloatspansetOut(functions.SpanSetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToIntspanset is MEOS floatspanset_to_intspanset.
func (x *FloatSpanSet) ToIntspanset() (*SpanSet, error) {
	_r0, _err := functions.FloatspansetToIntspanset(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS floatspanset_lower.
func (x *FloatSpanSet) Lower() (float64, error) {
	_r0, _err := functions.FloatspansetLower(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS floatspanset_upper.
func (x *FloatSpanSet) Upper() (float64, error) {
	_r0, _err := functions.FloatspansetUpper(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Width is MEOS floatspanset_width.
func (x *FloatSpanSet) Width(boundspan bool) (float64, error) {
	_r0, _err := functions.FloatspansetWidth(functions.SpanSetFromPointer(x.Pointer()), boundspan)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Ceil is MEOS floatspanset_ceil.
func (x *FloatSpanSet) Ceil() (*SpanSet, error) {
	_r0, _err := functions.FloatspansetCeil(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Floor is MEOS floatspanset_floor.
func (x *FloatSpanSet) Floor() (*SpanSet, error) {
	_r0, _err := functions.FloatspansetFloor(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Degrees is MEOS floatspanset_degrees.
func (x *FloatSpanSet) Degrees(normalize bool) (*SpanSet, error) {
	_r0, _err := functions.FloatspansetDegrees(functions.SpanSetFromPointer(x.Pointer()), normalize)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Radians is MEOS floatspanset_radians.
func (x *FloatSpanSet) Radians() (*SpanSet, error) {
	_r0, _err := functions.FloatspansetRadians(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Round is MEOS floatspanset_round.
func (x *FloatSpanSet) Round(maxdd int) (*SpanSet, error) {
	_r0, _err := functions.FloatspansetRound(functions.SpanSetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// ShiftScale is MEOS floatspanset_shift_scale.
func (x *FloatSpanSet) ShiftScale(shift float64, width float64, hasshift bool, haswidth bool) (*SpanSet, error) {
	_r0, _err := functions.FloatspansetShiftScale(functions.SpanSetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS floatspanset_bins.
func (x *FloatSpanSet) Bins(vsize float64, vorigin float64, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.FloatspansetBins(functions.SpanSetFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
