package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Geo struct {
	Value
}

// GeoFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func GeoFromPointer(p unsafe.Pointer) *Geo {
	if p == nil {
		return nil
	}
	v := &Geo{}
	v.ptr = p
	return v
}

// GeoAsEWKB is MEOS geo_as_ewkb.
func GeoAsEWKB(gs *TRGeometrySeqSet, endian string, size unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.GeoAsEWKB(functions.GeomFromPointer(gs.Pointer()), endian, size)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// GeoAsEWKT is MEOS geo_as_ewkt.
func GeoAsEWKT(gs *TRGeometrySeqSet, precision int) (string, error) {
	_r0, _err := functions.GeoAsEWKT(functions.GeomFromPointer(gs.Pointer()), precision)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeoAsGEOJSON is MEOS geo_as_geojson.
func GeoAsGEOJSON(gs *TRGeometrySeqSet, option int, precision int, srs string) (string, error) {
	_r0, _err := functions.GeoAsGeojson(functions.GeomFromPointer(gs.Pointer()), option, precision, srs)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeoAsHEXEWKB is MEOS geo_as_hexewkb.
func GeoAsHEXEWKB(gs *TRGeometrySeqSet, endian string) (string, error) {
	_r0, _err := functions.GeoAsHexewkb(functions.GeomFromPointer(gs.Pointer()), endian)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeoAsText is MEOS geo_as_text.
func GeoAsText(gs *TRGeometrySeqSet, precision int) (string, error) {
	_r0, _err := functions.GeoAsText(functions.GeomFromPointer(gs.Pointer()), precision)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeoFromEWKB is MEOS geo_from_ewkb.
func GeoFromEWKB(wkb unsafe.Pointer, wkb_size uint, srid int32) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoFromEWKB(wkb, wkb_size, srid)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoFromGEOJSON is MEOS geo_from_geojson.
func GeoFromGEOJSON(geojson string) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoFromGeojson(geojson)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoFromText is MEOS geo_from_text.
func GeoFromText(wkt string, srid int32) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoFromText(wkt, srid)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoOut is MEOS geo_out.
func GeoOut(gs *TRGeometrySeqSet) (string, error) {
	_r0, _err := functions.GeoOut(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeoCopy is MEOS geo_copy.
func GeoCopy(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoCopy(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoIsEmpty is MEOS geo_is_empty.
func GeoIsEmpty(gs *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeoIsEmpty(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeoIsUnitary is MEOS geo_is_unitary.
func GeoIsUnitary(gs *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeoIsUnitary(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeoTypename is MEOS geo_typename.
func GeoTypename(type_ int) (string, error) {
	_r0, _err := functions.GeoTypename(type_)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeoReverse is MEOS geo_reverse.
func GeoReverse(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoReverse(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoRound is MEOS geo_round.
func GeoRound(gs *TRGeometrySeqSet, maxdd int) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoRound(functions.GeomFromPointer(gs.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoSetSRID is MEOS geo_set_srid.
func GeoSetSRID(gs *TRGeometrySeqSet, srid int32) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoSetSRID(functions.GeomFromPointer(gs.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoSRID is MEOS geo_srid.
func GeoSRID(gs *TRGeometrySeqSet) (int32, error) {
	_r0, _err := functions.GeoSRID(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeoTransform is MEOS geo_transform.
func GeoTransform(geom *TRGeometrySeqSet, srid_to int32) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoTransform(functions.GeomFromPointer(geom.Pointer()), srid_to)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoTransformPipeline is MEOS geo_transform_pipeline.
func GeoTransformPipeline(gs *TRGeometrySeqSet, pipeline string, srid_to int32, is_forward bool) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoTransformPipeline(functions.GeomFromPointer(gs.Pointer()), pipeline, srid_to, is_forward)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoCollectGarray is MEOS geo_collect_garray.
func GeoCollectGarray(gsarr unsafe.Pointer, count int) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoCollectGarray(gsarr, count)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoMakelineGarray is MEOS geo_makeline_garray.
func GeoMakelineGarray(gsarr unsafe.Pointer, count int) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoMakelineGarray(gsarr, count)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoNumPoints is MEOS geo_num_points.
func GeoNumPoints(gs *TRGeometrySeqSet) (int, error) {
	_r0, _err := functions.GeoNumPoints(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeoNumGeos is MEOS geo_num_geos.
func GeoNumGeos(gs *TRGeometrySeqSet) (int, error) {
	_r0, _err := functions.GeoNumGeos(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeoGeoN is MEOS geo_geo_n.
func GeoGeoN(geom *TRGeometrySeqSet, n int) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoGeoN(functions.GeomFromPointer(geom.Pointer()), n)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoPointarr is MEOS geo_pointarr.
func GeoPointarr(gs *TRGeometrySeqSet, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.GeoPointarr(functions.GeomFromPointer(gs.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// GeoPoints is MEOS geo_points.
func GeoPoints(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeoPoints(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeoStboxes is MEOS geo_stboxes.
func GeoStboxes(gs *TRGeometrySeqSet, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.GeoStboxes(functions.GeomFromPointer(gs.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GeoSplitEachNStboxes is MEOS geo_split_each_n_stboxes.
func GeoSplitEachNStboxes(gs *TRGeometrySeqSet, elem_count int, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.GeoSplitEachNStboxes(functions.GeomFromPointer(gs.Pointer()), elem_count, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GeoSplitNStboxes is MEOS geo_split_n_stboxes.
func GeoSplitNStboxes(gs *TRGeometrySeqSet, box_count int, count unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.GeoSplitNStboxes(functions.GeomFromPointer(gs.Pointer()), box_count, count)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GeoEquals is MEOS geo_equals.
func GeoEquals(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (int, error) {
	_r0, _err := functions.GeoEquals(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeoSame is MEOS geo_same.
func GeoSame(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeoSame(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeoToSet is MEOS geo_to_set.
func GeoToSet(gs *TRGeometrySeqSet) (*Set, error) {
	_r0, _err := functions.GeoToSet(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// GeoTimestamptzToStbox is MEOS geo_timestamptz_to_stbox.
func GeoTimestamptzToStbox(gs *TRGeometrySeqSet, t int64) (*STBox, error) {
	_r0, _err := functions.GeoTimestamptzToSTBOX(functions.GeomFromPointer(gs.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GeoTstzspanToStbox is MEOS geo_tstzspan_to_stbox.
func GeoTstzspanToStbox(gs *TRGeometrySeqSet, s *Span) (*STBox, error) {
	_r0, _err := functions.GeoTstzspanToSTBOX(functions.GeomFromPointer(gs.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GeoToStbox is MEOS geo_to_stbox.
func GeoToStbox(gs *TRGeometrySeqSet) (*STBox, error) {
	_r0, _err := functions.GeoToSTBOX(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// GeoClusterKmeans is MEOS geo_cluster_kmeans.
func GeoClusterKmeans(geoms unsafe.Pointer, ngeoms uint32, k uint32, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.GeoClusterKmeans(geoms, ngeoms, k, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// GeoClusterDbscan is MEOS geo_cluster_dbscan.
func GeoClusterDbscan(geoms unsafe.Pointer, ngeoms uint32, tolerance float64, minpoints int, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.GeoClusterDbscan(geoms, ngeoms, tolerance, minpoints, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// GeoClusterIntersecting is MEOS geo_cluster_intersecting.
func GeoClusterIntersecting(geoms unsafe.Pointer, ngeoms uint32, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.GeoClusterIntersecting(geoms, ngeoms, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// GeoClusterWithin is MEOS geo_cluster_within.
func GeoClusterWithin(geoms unsafe.Pointer, ngeoms uint32, tolerance float64, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.GeoClusterWithin(geoms, ngeoms, tolerance, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// GeoToH3indexCell is MEOS geo_to_h3index_cell.
func GeoToH3indexCell(point *TRGeometrySeqSet, resolution int32) (uint64, error) {
	_r0, _err := functions.GeoToH3indexCell(functions.GeomFromPointer(point.Pointer()), resolution)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeoToH3indexSet is MEOS geo_to_h3index_set.
func GeoToH3indexSet(gs *TRGeometrySeqSet, resolution int32) (*Set, error) {
	_r0, _err := functions.GeoToH3indexSet(functions.GeomFromPointer(gs.Pointer()), resolution)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// GeoToQuadbinCell is MEOS geo_to_quadbin_cell.
func GeoToQuadbinCell(point *TRGeometrySeqSet, resolution int32) (uint64, error) {
	_r0, _err := functions.GeoToQuadbinCell(functions.GeomFromPointer(point.Pointer()), resolution)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}
