package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type GeogSet struct {
	Set
}

// GeogSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func GeogSetFromPointer(p unsafe.Pointer) *GeogSet {
	if p == nil {
		return nil
	}
	v := &GeogSet{}
	v.ptr = p
	return v
}

// GeogSetIn is MEOS geogset_in.
func GeogSetIn(str string) (*Set, error) {
	_r0, _err := functions.GeogsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
