package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Geography struct {
	Geo
}

// GeographyFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func GeographyFromPointer(p unsafe.Pointer) *Geography {
	if p == nil {
		return nil
	}
	v := &Geography{}
	v.ptr = p
	return v
}

// GeographyFromHEXEWKB is MEOS geog_from_hexewkb.
func GeographyFromHEXEWKB(wkt string) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeogFromHexewkb(wkt)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeographyIn is MEOS geog_in.
func GeographyIn(str string, typmod int32) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeogIn(str, typmod)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeographyToGeom is MEOS geog_to_geom.
func GeographyToGeom(geog *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeogToGeom(functions.GeomFromPointer(geog.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeographyArea is MEOS geog_area.
func GeographyArea(gs *TRGeometrySeqSet, use_spheroid bool) (float64, error) {
	_r0, _err := functions.GeogArea(functions.GeomFromPointer(gs.Pointer()), use_spheroid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeographyCentroid is MEOS geog_centroid.
func GeographyCentroid(gs *TRGeometrySeqSet, use_spheroid bool) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeogCentroid(functions.GeomFromPointer(gs.Pointer()), use_spheroid)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeographyLength is MEOS geog_length.
func GeographyLength(gs *TRGeometrySeqSet, use_spheroid bool) (float64, error) {
	_r0, _err := functions.GeogLength(functions.GeomFromPointer(gs.Pointer()), use_spheroid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeographyPerimeter is MEOS geog_perimeter.
func GeographyPerimeter(gs *TRGeometrySeqSet, use_spheroid bool) (float64, error) {
	_r0, _err := functions.GeogPerimeter(functions.GeomFromPointer(gs.Pointer()), use_spheroid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeographyArrayUnion is MEOS geog_array_union.
func GeographyArrayUnion(gsarr unsafe.Pointer, count int) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeogArrayUnion(gsarr, count)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeographyDwithin is MEOS geog_dwithin.
func GeographyDwithin(g1 *TRGeometrySeqSet, g2 *TRGeometrySeqSet, tolerance float64, use_spheroid bool) (bool, error) {
	_r0, _err := functions.GeogDwithin(functions.GeomFromPointer(g1.Pointer()), functions.GeomFromPointer(g2.Pointer()), tolerance, use_spheroid)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeographyDistance is MEOS geog_distance.
func GeographyDistance(g1 *TRGeometrySeqSet, g2 *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeogDistance(functions.GeomFromPointer(g1.Pointer()), functions.GeomFromPointer(g2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}
