package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Geometry struct {
	Geo
}

// GeometryFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func GeometryFromPointer(p unsafe.Pointer) *Geometry {
	if p == nil {
		return nil
	}
	v := &Geometry{}
	v.ptr = p
	return v
}

// GeometryFromHEXEWKB is MEOS geom_from_hexewkb.
func GeometryFromHEXEWKB(wkt string) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomFromHexewkb(wkt)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryIn is MEOS geom_in.
func GeometryIn(str string, typmod int32) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomIn(str, typmod)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryToGeog is MEOS geom_to_geog.
func GeometryToGeog(geom *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomToGeog(functions.GeomFromPointer(geom.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryAzimuth is MEOS geom_azimuth.
func GeometryAzimuth(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (float64, bool, error) {
	_found, _value, _err := functions.GeomAzimuth(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// GeometryArea is MEOS geom_area.
func GeometryArea(gs *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeomArea(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeometryLength is MEOS geom_length.
func GeometryLength(gs *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeomLength(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeometryPerimeter is MEOS geom_perimeter.
func GeometryPerimeter(gs *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeomPerimeter(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeometryArrayUnion is MEOS geom_array_union.
func GeometryArrayUnion(gsarr unsafe.Pointer, count int) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomArrayUnion(gsarr, count)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryBoundary is MEOS geom_boundary.
func GeometryBoundary(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomBoundary(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryBuffer is MEOS geom_buffer.
func GeometryBuffer(gs *TRGeometrySeqSet, size float64, params string) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomBuffer(functions.GeomFromPointer(gs.Pointer()), size, params)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryCentroid is MEOS geom_centroid.
func GeometryCentroid(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomCentroid(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryConvexHull is MEOS geom_convex_hull.
func GeometryConvexHull(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomConvexHull(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryDifference2d is MEOS geom_difference2d.
func GeometryDifference2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomDifference2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryIsSimple is MEOS geom_is_simple.
func GeometryIsSimple(gs *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeomIsSimple(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryIntersection2d is MEOS geom_intersection2d.
func GeometryIntersection2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomIntersection2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryIntersection2dColl is MEOS geom_intersection2d_coll.
func GeometryIntersection2dColl(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomIntersection2dColl(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryMinBoundingRadius is MEOS geom_min_bounding_radius.
func GeometryMinBoundingRadius(geom *TRGeometrySeqSet, radius unsafe.Pointer) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomMinBoundingRadius(functions.GeomFromPointer(geom.Pointer()), radius)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryOrientedEnvelope is MEOS geom_oriented_envelope.
func GeometryOrientedEnvelope(gs *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomOrientedEnvelope(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryShortestline2d is MEOS geom_shortestline2d.
func GeometryShortestline2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomShortestline2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryShortestline3d is MEOS geom_shortestline3d.
func GeometryShortestline3d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomShortestline3d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryUnaryUnion is MEOS geom_unary_union.
func GeometryUnaryUnion(gs *TRGeometrySeqSet, prec float64) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.GeomUnaryUnion(functions.GeomFromPointer(gs.Pointer()), prec)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// GeometryCovers is MEOS geom_covers.
func GeometryCovers(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeomCovers(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryDisjoint2d is MEOS geom_disjoint2d.
func GeometryDisjoint2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeomDisjoint2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryDwithin is MEOS geom_dwithin.
func GeometryDwithin(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet, tolerance float64) (bool, error) {
	_r0, _err := functions.GeomDwithin(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()), tolerance)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryDwithin2d is MEOS geom_dwithin2d.
func GeometryDwithin2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet, tolerance float64) (bool, error) {
	_r0, _err := functions.GeomDwithin2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()), tolerance)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryDwithin3d is MEOS geom_dwithin3d.
func GeometryDwithin3d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet, tolerance float64) (bool, error) {
	_r0, _err := functions.GeomDwithin3d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()), tolerance)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryIntersects2d is MEOS geom_intersects2d.
func GeometryIntersects2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeomIntersects2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryIntersects3d is MEOS geom_intersects3d.
func GeometryIntersects3d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeomIntersects3d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryRelate is MEOS geom_relate.
func GeometryRelate(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (string, error) {
	_r0, _err := functions.GeomRelate(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// GeometryRelatePattern is MEOS geom_relate_pattern.
func GeometryRelatePattern(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet, patt string) (bool, error) {
	_r0, _err := functions.GeomRelatePattern(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()), patt)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryTouches is MEOS geom_touches.
func GeometryTouches(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (bool, error) {
	_r0, _err := functions.GeomTouches(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GeometryDistance2d is MEOS geom_distance2d.
func GeometryDistance2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeomDistance2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeometryMaxDistance2d is MEOS geom_max_distance2d.
func GeometryMaxDistance2d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeomMaxDistance2d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeometryDistance3d is MEOS geom_distance3d.
func GeometryDistance3d(gs1 *TRGeometrySeqSet, gs2 *TRGeometrySeqSet) (float64, error) {
	_r0, _err := functions.GeomDistance3d(functions.GeomFromPointer(gs1.Pointer()), functions.GeomFromPointer(gs2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GeometryToCbuffer is MEOS geom_to_cbuffer.
func GeometryToCbuffer(gs *TRGeometrySeqSet) (*Cbuffer, error) {
	_r0, _err := functions.GeomToCbuffer(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// GeometryToNsegment is MEOS geom_to_nsegment.
func GeometryToNsegment(gs *TRGeometrySeqSet) (*Nsegment, error) {
	_r0, _err := functions.GeomToNsegment(functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return NsegmentFromPointer(_r0.Pointer()), nil
}

// GeometryTposeToTrgeometry is MEOS geometry_tpose_to_trgeometry.
func GeometryTposeToTrgeometry(gs *TRGeometrySeqSet, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.GeometryTposeToTrgeometry(functions.GeomFromPointer(gs.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
