package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type IntSpanSet struct {
	SpanSet
}

// IntSpanSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func IntSpanSetFromPointer(p unsafe.Pointer) *IntSpanSet {
	if p == nil {
		return nil
	}
	v := &IntSpanSet{}
	v.ptr = p
	return v
}

// IntSpanSetIn is MEOS intspanset_in.
func IntSpanSetIn(str string) (*SpanSet, error) {
	_r0, _err := functions.IntspansetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS intspanset_out.
func (x *IntSpanSet) Out() (string, error) {
	_r0, _err := functions.IntspansetOut(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToFloatspanset is MEOS intspanset_to_floatspanset.
func (x *IntSpanSet) ToFloatspanset() (*SpanSet, error) {
	_r0, _err := functions.IntspansetToFloatspanset(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS intspanset_lower.
func (x *IntSpanSet) Lower() (int, error) {
	_r0, _err := functions.IntspansetLower(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS intspanset_upper.
func (x *IntSpanSet) Upper() (int, error) {
	_r0, _err := functions.IntspansetUpper(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Width is MEOS intspanset_width.
func (x *IntSpanSet) Width(boundspan bool) (int, error) {
	_r0, _err := functions.IntspansetWidth(functions.SpanSetFromPointer(x.Pointer()), boundspan)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS intspanset_shift_scale.
func (x *IntSpanSet) ShiftScale(shift int, width int, hasshift bool, haswidth bool) (*SpanSet, error) {
	_r0, _err := functions.IntspansetShiftScale(functions.SpanSetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS intspanset_bins.
func (x *IntSpanSet) Bins(vsize int, vorigin int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.IntspansetBins(functions.SpanSetFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
