package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type IntSet struct {
	Set
}

// IntSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func IntSetFromPointer(p unsafe.Pointer) *IntSet {
	if p == nil {
		return nil
	}
	v := &IntSet{}
	v.ptr = p
	return v
}

// IntSetIn is MEOS intset_in.
func IntSetIn(str string) (*Set, error) {
	_r0, _err := functions.IntsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS intset_out.
func (x *IntSet) Out() (string, error) {
	_r0, _err := functions.IntsetOut(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// IntSetMake is MEOS intset_make.
func IntSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.IntsetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToFloatset is MEOS intset_to_floatset.
func (x *IntSet) ToFloatset() (*Set, error) {
	_r0, _err := functions.IntsetToFloatset(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS intset_end_value.
func (x *IntSet) EndValue() (int, error) {
	_r0, _err := functions.IntsetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS intset_start_value.
func (x *IntSet) StartValue() (int, error) {
	_r0, _err := functions.IntsetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueN is MEOS intset_value_n.
func (x *IntSet) ValueN(n int) (int, bool, error) {
	_found, _value, _err := functions.IntsetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS intset_values.
func (x *IntSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.IntsetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS intset_shift_scale.
func (x *IntSet) ShiftScale(shift int, width int, hasshift bool, haswidth bool) (*Set, error) {
	_r0, _err := functions.IntsetShiftScale(functions.SetFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
