package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type IntSpan struct {
	Span
}

// IntSpanFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func IntSpanFromPointer(p unsafe.Pointer) *IntSpan {
	if p == nil {
		return nil
	}
	v := &IntSpan{}
	v.ptr = p
	return v
}

// Expand is MEOS intspan_expand.
func (x *IntSpan) Expand(value int32) (*Span, error) {
	_r0, _err := functions.IntspanExpand(functions.SpanFromPointer(x.Pointer()), value)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// IntSpanIn is MEOS intspan_in.
func IntSpanIn(str string) (*Span, error) {
	_r0, _err := functions.IntspanIn(str)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Out is MEOS intspan_out.
func (x *IntSpan) Out() (string, error) {
	_r0, _err := functions.IntspanOut(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// IntSpanMake is MEOS intspan_make.
func IntSpanMake(lower int, upper int, lower_inc bool, upper_inc bool) (*Span, error) {
	_r0, _err := functions.IntspanMake(lower, upper, lower_inc, upper_inc)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToFloatspan is MEOS intspan_to_floatspan.
func (x *IntSpan) ToFloatspan() (*Span, error) {
	_r0, _err := functions.IntspanToFloatspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToBigintspan is MEOS intspan_to_bigintspan.
func (x *IntSpan) ToBigintspan() (*Span, error) {
	_r0, _err := functions.IntspanToBigintspan(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS intspan_lower.
func (x *IntSpan) Lower() (int, error) {
	_r0, _err := functions.IntspanLower(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Upper is MEOS intspan_upper.
func (x *IntSpan) Upper() (int, error) {
	_r0, _err := functions.IntspanUpper(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Width is MEOS intspan_width.
func (x *IntSpan) Width() (int, error) {
	_r0, _err := functions.IntspanWidth(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ShiftScale is MEOS intspan_shift_scale.
func (x *IntSpan) ShiftScale(shift int, width int, hasshift bool, haswidth bool) (*Span, error) {
	_r0, _err := functions.IntspanShiftScale(functions.SpanFromPointer(x.Pointer()), shift, width, hasshift, haswidth)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Bins is MEOS intspan_bins.
func (x *IntSpan) Bins(vsize int, vorigin int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.IntspanBins(functions.SpanFromPointer(x.Pointer()), vsize, vorigin, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}
