package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Jsonb struct {
	Value
}

// JsonbFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func JsonbFromPointer(p unsafe.Pointer) *Jsonb {
	if p == nil {
		return nil
	}
	v := &Jsonb{}
	v.ptr = p
	return v
}

// JsonbFromText is MEOS jsonb_from_text.
func JsonbFromText(txt string, unique_keys bool) (*Jsonb, error) {
	_r0, _err := functions.JsonbFromText(txt, unique_keys)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// JsonbIn is MEOS jsonb_in.
func JsonbIn(str string) (*Jsonb, error) {
	_r0, _err := functions.JsonbIn(str)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// Out is MEOS jsonb_out.
func (x *Jsonb) Out() (string, error) {
	_r0, _err := functions.JsonbOut(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Copy is MEOS jsonb_copy.
func (x *Jsonb) Copy() (*Jsonb, error) {
	_r0, _err := functions.JsonbCopy(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// JsonbMake is MEOS jsonb_make.
func JsonbMake(keys_vals unsafe.Pointer, count int) (*Jsonb, error) {
	_r0, _err := functions.JsonbMake(keys_vals, count)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// JsonbMakeTwoArg is MEOS jsonb_make_two_arg.
func JsonbMakeTwoArg(keys unsafe.Pointer, values unsafe.Pointer, count int) (*Jsonb, error) {
	_r0, _err := functions.JsonbMakeTwoArg(keys, values, count)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// ToBool is MEOS jsonb_to_bool.
func (x *Jsonb) ToBool() (bool, error) {
	_r0, _err := functions.JsonbToBool(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ToCstring is MEOS jsonb_to_cstring.
func (x *Jsonb) ToCstring() (string, error) {
	_r0, _err := functions.JsonbToCstring(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToInt16 is MEOS jsonb_to_int16.
func (x *Jsonb) ToInt16() (int16, error) {
	_r0, _err := functions.JsonbToInt16(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToInt32 is MEOS jsonb_to_int32.
func (x *Jsonb) ToInt32() (int32, error) {
	_r0, _err := functions.JsonbToInt32(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToInt64 is MEOS jsonb_to_int64.
func (x *Jsonb) ToInt64() (int64, error) {
	_r0, _err := functions.JsonbToInt64(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToText is MEOS jsonb_to_text.
func (x *Jsonb) ToText() (string, error) {
	_r0, _err := functions.JsonbToText(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ArrayElement is MEOS jsonb_array_element.
func (x *Jsonb) ArrayElement(element int) (*Jsonb, error) {
	_r0, _err := functions.JsonbArrayElement(functions.JsonbFromPointer(x.Pointer()), element)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// ArrayElementText is MEOS jsonb_array_element_text.
func (x *Jsonb) ArrayElementText(element int) (string, error) {
	_r0, _err := functions.JsonbArrayElementText(functions.JsonbFromPointer(x.Pointer()), element)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ArrayElements is MEOS jsonb_array_elements.
func (x *Jsonb) ArrayElements(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.JsonbArrayElements(functions.JsonbFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ArrayElementsText is MEOS jsonb_array_elements_text.
func (x *Jsonb) ArrayElementsText(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.JsonbArrayElementsText(functions.JsonbFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ArrayLength is MEOS jsonb_array_length.
func (x *Jsonb) ArrayLength() (int, error) {
	_r0, _err := functions.JsonbArrayLength(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Contained is MEOS jsonb_contained.
func (x *Jsonb) Contained(jb2 *Jsonb) (bool, error) {
	_r0, _err := functions.JsonbContained(functions.JsonbFromPointer(x.Pointer()), functions.JsonbFromPointer(jb2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Each is MEOS jsonb_each.
func (x *Jsonb) Each(values unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.JsonbEach(functions.JsonbFromPointer(x.Pointer()), values, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// EachText is MEOS jsonb_each_text.
func (x *Jsonb) EachText(values unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.JsonbEachText(functions.JsonbFromPointer(x.Pointer()), values, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Exists is MEOS jsonb_exists.
func (x *Jsonb) Exists(key string) (bool, error) {
	_r0, _err := functions.JsonbExists(functions.JsonbFromPointer(x.Pointer()), key)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ExistsArray is MEOS jsonb_exists_array.
func (x *Jsonb) ExistsArray(keys_elems unsafe.Pointer, keys_len int, any bool) (bool, error) {
	_r0, _err := functions.JsonbExistsArray(functions.JsonbFromPointer(x.Pointer()), keys_elems, keys_len, any)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ExtractPath is MEOS jsonb_extract_path.
func (x *Jsonb) ExtractPath(path_elems unsafe.Pointer, path_len int) (*Jsonb, error) {
	_r0, _err := functions.JsonbExtractPath(functions.JsonbFromPointer(x.Pointer()), path_elems, path_len)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// ExtractPathText is MEOS jsonb_extract_path_text.
func (x *Jsonb) ExtractPathText(path_elems unsafe.Pointer, path_len int) (string, error) {
	_r0, _err := functions.JsonbExtractPathText(functions.JsonbFromPointer(x.Pointer()), path_elems, path_len)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Hash is MEOS jsonb_hash.
func (x *Jsonb) Hash() (uint32, error) {
	_r0, _err := functions.JsonbHash(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS jsonb_hash_extended.
func (x *Jsonb) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.JsonbHashExtended(functions.JsonbFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ObjectField is MEOS jsonb_object_field.
func (x *Jsonb) ObjectField(key string) (*Jsonb, error) {
	_r0, _err := functions.JsonbObjectField(functions.JsonbFromPointer(x.Pointer()), key)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// ObjectFieldText is MEOS jsonb_object_field_text.
func (x *Jsonb) ObjectFieldText(key string) (string, error) {
	_r0, _err := functions.JsonbObjectFieldText(functions.JsonbFromPointer(x.Pointer()), key)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ObjectKeys is MEOS jsonb_object_keys.
func (x *Jsonb) ObjectKeys(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.JsonbObjectKeys(functions.JsonbFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Concat is MEOS jsonb_concat.
func (x *Jsonb) Concat(jb2 *Jsonb) (*Jsonb, error) {
	_r0, _err := functions.JsonbConcat(functions.JsonbFromPointer(x.Pointer()), functions.JsonbFromPointer(jb2.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// Delete is MEOS jsonb_delete.
func (x *Jsonb) Delete(key string) (*Jsonb, error) {
	_r0, _err := functions.JsonbDelete(functions.JsonbFromPointer(x.Pointer()), key)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// DeleteArray is MEOS jsonb_delete_array.
func (x *Jsonb) DeleteArray(keys_elems unsafe.Pointer, keys_len int) (*Jsonb, error) {
	_r0, _err := functions.JsonbDeleteArray(functions.JsonbFromPointer(x.Pointer()), keys_elems, keys_len)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// DeleteIndex is MEOS jsonb_delete_index.
func (x *Jsonb) DeleteIndex(idx int) (*Jsonb, error) {
	_r0, _err := functions.JsonbDeleteIndex(functions.JsonbFromPointer(x.Pointer()), idx)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// DeletePath is MEOS jsonb_delete_path.
func (x *Jsonb) DeletePath(path_elems unsafe.Pointer, path_len int) (*Jsonb, error) {
	_r0, _err := functions.JsonbDeletePath(functions.JsonbFromPointer(x.Pointer()), path_elems, path_len)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// Insert is MEOS jsonb_insert.
func (x *Jsonb) Insert(path_elems unsafe.Pointer, path_len int, newjb *Jsonb, after bool) (*Jsonb, error) {
	_r0, _err := functions.JsonbInsert(functions.JsonbFromPointer(x.Pointer()), path_elems, path_len, functions.JsonbFromPointer(newjb.Pointer()), after)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// Pretty is MEOS jsonb_pretty.
func (x *Jsonb) Pretty() (string, error) {
	_r0, _err := functions.JsonbPretty(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// Set is MEOS jsonb_set.
func (x *Jsonb) Set(path_elems unsafe.Pointer, path_len int, newjb *Jsonb, create bool) (*Jsonb, error) {
	_r0, _err := functions.JsonbSet(functions.JsonbFromPointer(x.Pointer()), path_elems, path_len, functions.JsonbFromPointer(newjb.Pointer()), create)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// SetLax is MEOS jsonb_set_lax.
func (x *Jsonb) SetLax(path_elems unsafe.Pointer, path_len int, newjb *Jsonb, create bool, handle_null string) (*Jsonb, error) {
	_r0, _err := functions.JsonbSetLax(functions.JsonbFromPointer(x.Pointer()), path_elems, path_len, functions.JsonbFromPointer(newjb.Pointer()), create, handle_null)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// StripNulls is MEOS jsonb_strip_nulls.
func (x *Jsonb) StripNulls(strip_in_arrays bool) (*Jsonb, error) {
	_r0, _err := functions.JsonbStripNulls(functions.JsonbFromPointer(x.Pointer()), strip_in_arrays)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// PathExists is MEOS jsonb_path_exists.
func (x *Jsonb) PathExists(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (int, error) {
	_r0, _err := functions.JsonbPathExists(functions.JsonbFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PathMatch is MEOS jsonb_path_match.
func (x *Jsonb) PathMatch(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (bool, error) {
	_r0, _err := functions.JsonbPathMatch(functions.JsonbFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PathQueryAll is MEOS jsonb_path_query_all.
func (x *Jsonb) PathQueryAll(jp *JsonPath, vars *Jsonb, silent bool, tz bool, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.JsonbPathQueryAll(functions.JsonbFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PathQueryArray is MEOS jsonb_path_query_array.
func (x *Jsonb) PathQueryArray(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (*Jsonb, error) {
	_r0, _err := functions.JsonbPathQueryArray(functions.JsonbFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// PathQueryFirst is MEOS jsonb_path_query_first.
func (x *Jsonb) PathQueryFirst(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (*Jsonb, error) {
	_r0, _err := functions.JsonbPathQueryFirst(functions.JsonbFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// ToSet is MEOS jsonb_to_set.
func (x *Jsonb) ToSet() (*Set, error) {
	_r0, _err := functions.JsonbToSet(functions.JsonbFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
