package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type JsonPath struct {
	Value
}

// JsonPathFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func JsonPathFromPointer(p unsafe.Pointer) *JsonPath {
	if p == nil {
		return nil
	}
	v := &JsonPath{}
	v.ptr = p
	return v
}

// JsonPathIn is MEOS jsonpath_in.
func JsonPathIn(str string) (*JsonPath, error) {
	_r0, _err := functions.JsonpathIn(str)
	if _err != nil {
		return nil, _err
	}
	return JsonPathFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS jsonpath_copy.
func (x *JsonPath) Copy() (*JsonPath, error) {
	_r0, _err := functions.JsonpathCopy(functions.JsonPathFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return JsonPathFromPointer(_r0.Pointer()), nil
}

// Out is MEOS jsonpath_out.
func (x *JsonPath) Out() (string, error) {
	_r0, _err := functions.JsonpathOut(functions.JsonPathFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}
