package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type MeosArray struct {
	Value
}

// MeosArrayFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func MeosArrayFromPointer(p unsafe.Pointer) *MeosArray {
	if p == nil {
		return nil
	}
	v := &MeosArray{}
	v.ptr = p
	return v
}

// MeosArrayCreate is MEOS meos_array_create.
func MeosArrayCreate(elem_size int) (*MeosArray, error) {
	_r0, _err := functions.MeosArrayCreate(elem_size)
	if _err != nil {
		return nil, _err
	}
	return MeosArrayFromPointer(_r0.Pointer()), nil
}

// Add is MEOS meos_array_add.
func (x *MeosArray) Add(value unsafe.Pointer) error {
	return functions.MeosArrayAdd(functions.MeosArrayFromPointer(x.Pointer()), value)
}

// Get is MEOS meos_array_get.
func (x *MeosArray) Get(n int) (unsafe.Pointer, error) {
	_r0, _err := functions.MeosArrayGet(functions.MeosArrayFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Count is MEOS meos_array_count.
func (x *MeosArray) Count() (int, error) {
	_r0, _err := functions.MeosArrayCount(functions.MeosArrayFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Reset is MEOS meos_array_reset.
func (x *MeosArray) Reset() error {
	return functions.MeosArrayReset(functions.MeosArrayFromPointer(x.Pointer()))
}

// ResetFree is MEOS meos_array_reset_free.
func (x *MeosArray) ResetFree() error {
	return functions.MeosArrayResetFree(functions.MeosArrayFromPointer(x.Pointer()))
}

// Destroy is MEOS meos_array_destroy.
func (x *MeosArray) Destroy() error {
	return functions.MeosArrayDestroy(functions.MeosArrayFromPointer(x.Pointer()))
}

// DestroyFree is MEOS meos_array_destroy_free.
func (x *MeosArray) DestroyFree() error {
	return functions.MeosArrayDestroyFree(functions.MeosArrayFromPointer(x.Pointer()))
}
