package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import "unsafe"

// handle is the MEOS value every class in this package stands for.
//
// cgo types are package-scoped, so the *C.Temporal the functions package
// holds and one declared here would be DIFFERENT Go types. The untyped
// pointer is the only currency the two packages share, which is why each
// class carries one and hands it across at every call.
type handle struct {
	ptr unsafe.Pointer
}

// Pointer answers the MEOS value this handle stands for, or nil.
func (h *handle) Pointer() unsafe.Pointer {
	if h == nil {
		return nil
	}
	return h.ptr
}
