package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Npoint struct {
	Value
}

// NpointFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func NpointFromPointer(p unsafe.Pointer) *Npoint {
	if p == nil {
		return nil
	}
	v := &Npoint{}
	v.ptr = p
	return v
}

// AsEWKT is MEOS npoint_as_ewkt.
func (x *Npoint) AsEWKT(maxdd int) (string, error) {
	_r0, _err := functions.NpointAsEWKT(functions.NpointFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsHEXWKB is MEOS npoint_as_hexwkb.
func (x *Npoint) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.NpointAsHexwkb(functions.NpointFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsText is MEOS npoint_as_text.
func (x *Npoint) AsText(maxdd int) (string, error) {
	_r0, _err := functions.NpointAsText(functions.NpointFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS npoint_as_wkb.
func (x *Npoint) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.NpointAsWKB(functions.NpointFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// NpointFromHEXWKB is MEOS npoint_from_hexwkb.
func NpointFromHEXWKB(hexwkb string) (*Npoint, error) {
	_r0, _err := functions.NpointFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// NpointFromWKB is MEOS npoint_from_wkb.
func NpointFromWKB(wkb unsafe.Pointer, size uint) (*Npoint, error) {
	_r0, _err := functions.NpointFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// NpointIn is MEOS npoint_in.
func NpointIn(str string) (*Npoint, error) {
	_r0, _err := functions.NpointIn(str)
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// Out is MEOS npoint_out.
func (x *Npoint) Out(maxdd int) (string, error) {
	_r0, _err := functions.NpointOut(functions.NpointFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// NpointMake is MEOS npoint_make.
func NpointMake(rid int64, pos float64) (*Npoint, error) {
	_r0, _err := functions.NpointMake(rid, pos)
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// ToGeompoint is MEOS npoint_to_geompoint.
func (x *Npoint) ToGeompoint() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.NpointToGeompoint(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ToNsegment is MEOS npoint_to_nsegment.
func (x *Npoint) ToNsegment() (*Nsegment, error) {
	_r0, _err := functions.NpointToNsegment(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return NsegmentFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS npoint_to_stbox.
func (x *Npoint) ToStbox() (*STBox, error) {
	_r0, _err := functions.NpointToSTBOX(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS npoint_hash.
func (x *Npoint) Hash() (uint32, error) {
	_r0, _err := functions.NpointHash(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS npoint_hash_extended.
func (x *Npoint) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.NpointHashExtended(functions.NpointFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Position is MEOS npoint_position.
func (x *Npoint) Position() (float64, error) {
	_r0, _err := functions.NpointPosition(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Route is MEOS npoint_route.
func (x *Npoint) Route() (int64, error) {
	_r0, _err := functions.NpointRoute(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Round is MEOS npoint_round.
func (x *Npoint) Round(maxdd int) (*Npoint, error) {
	_r0, _err := functions.NpointRound(functions.NpointFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// SRID is MEOS npoint_srid.
func (x *Npoint) SRID() (int32, error) {
	_r0, _err := functions.NpointSRID(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// TimestamptzToStbox is MEOS npoint_timestamptz_to_stbox.
func (x *Npoint) TimestamptzToStbox(t int64) (*STBox, error) {
	_r0, _err := functions.NpointTimestamptzToSTBOX(functions.NpointFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// TstzspanToStbox is MEOS npoint_tstzspan_to_stbox.
func (x *Npoint) TstzspanToStbox(s *Span) (*STBox, error) {
	_r0, _err := functions.NpointTstzspanToSTBOX(functions.NpointFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS npoint_cmp.
func (x *Npoint) Cmp(np2 *Npoint) (int, error) {
	_r0, _err := functions.NpointCmp(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS npoint_eq.
func (x *Npoint) Eq(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointEq(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS npoint_ge.
func (x *Npoint) Ge(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointGe(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS npoint_gt.
func (x *Npoint) Gt(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointGt(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS npoint_le.
func (x *Npoint) Le(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointLe(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS npoint_lt.
func (x *Npoint) Lt(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointLt(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS npoint_ne.
func (x *Npoint) Ne(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointNe(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Same is MEOS npoint_same.
func (x *Npoint) Same(np2 *Npoint) (bool, error) {
	_r0, _err := functions.NpointSame(functions.NpointFromPointer(x.Pointer()), functions.NpointFromPointer(np2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ToSet is MEOS npoint_to_set.
func (x *Npoint) ToSet() (*Set, error) {
	_r0, _err := functions.NpointToSet(functions.NpointFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
