package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type NpointSet struct {
	Set
}

// NpointSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func NpointSetFromPointer(p unsafe.Pointer) *NpointSet {
	if p == nil {
		return nil
	}
	v := &NpointSet{}
	v.ptr = p
	return v
}

// NpointSetIn is MEOS npointset_in.
func NpointSetIn(str string) (*Set, error) {
	_r0, _err := functions.NpointsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS npointset_out.
func (x *NpointSet) Out(maxdd int) (string, error) {
	_r0, _err := functions.NpointsetOut(functions.SetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// NpointSetMake is MEOS npointset_make.
func NpointSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.NpointsetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS npointset_end_value.
func (x *NpointSet) EndValue() (*Npoint, error) {
	_r0, _err := functions.NpointsetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// Routes is MEOS npointset_routes.
func (x *NpointSet) Routes() (*Set, error) {
	_r0, _err := functions.NpointsetRoutes(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS npointset_start_value.
func (x *NpointSet) StartValue() (*Npoint, error) {
	_r0, _err := functions.NpointsetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// ValueN is MEOS npointset_value_n.
func (x *NpointSet) ValueN(n int) (*Npoint, bool, error) {
	_found, _value, _err := functions.NpointsetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return NpointFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS npointset_values.
func (x *NpointSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.NpointsetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
