package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Nsegment struct {
	Value
}

// NsegmentFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func NsegmentFromPointer(p unsafe.Pointer) *Nsegment {
	if p == nil {
		return nil
	}
	v := &Nsegment{}
	v.ptr = p
	return v
}

// NsegmentIn is MEOS nsegment_in.
func NsegmentIn(str string) (*Nsegment, error) {
	_r0, _err := functions.NsegmentIn(str)
	if _err != nil {
		return nil, _err
	}
	return NsegmentFromPointer(_r0.Pointer()), nil
}

// Out is MEOS nsegment_out.
func (x *Nsegment) Out(maxdd int) (string, error) {
	_r0, _err := functions.NsegmentOut(functions.NsegmentFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// NsegmentMake is MEOS nsegment_make.
func NsegmentMake(rid int64, pos1 float64, pos2 float64) (*Nsegment, error) {
	_r0, _err := functions.NsegmentMake(rid, pos1, pos2)
	if _err != nil {
		return nil, _err
	}
	return NsegmentFromPointer(_r0.Pointer()), nil
}

// ToGeom is MEOS nsegment_to_geom.
func (x *Nsegment) ToGeom() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.NsegmentToGeom(functions.NsegmentFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS nsegment_to_stbox.
func (x *Nsegment) ToStbox() (*STBox, error) {
	_r0, _err := functions.NsegmentToSTBOX(functions.NsegmentFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// EndPosition is MEOS nsegment_end_position.
func (x *Nsegment) EndPosition() (float64, error) {
	_r0, _err := functions.NsegmentEndPosition(functions.NsegmentFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Route is MEOS nsegment_route.
func (x *Nsegment) Route() (int64, error) {
	_r0, _err := functions.NsegmentRoute(functions.NsegmentFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartPosition is MEOS nsegment_start_position.
func (x *Nsegment) StartPosition() (float64, error) {
	_r0, _err := functions.NsegmentStartPosition(functions.NsegmentFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Round is MEOS nsegment_round.
func (x *Nsegment) Round(maxdd int) (*Nsegment, error) {
	_r0, _err := functions.NsegmentRound(functions.NsegmentFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return NsegmentFromPointer(_r0.Pointer()), nil
}

// SRID is MEOS nsegment_srid.
func (x *Nsegment) SRID() (int32, error) {
	_r0, _err := functions.NsegmentSRID(functions.NsegmentFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Cmp is MEOS nsegment_cmp.
func (x *Nsegment) Cmp(ns2 *Nsegment) (int, error) {
	_r0, _err := functions.NsegmentCmp(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS nsegment_eq.
func (x *Nsegment) Eq(ns2 *Nsegment) (bool, error) {
	_r0, _err := functions.NsegmentEq(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS nsegment_ge.
func (x *Nsegment) Ge(ns2 *Nsegment) (bool, error) {
	_r0, _err := functions.NsegmentGe(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS nsegment_gt.
func (x *Nsegment) Gt(ns2 *Nsegment) (bool, error) {
	_r0, _err := functions.NsegmentGt(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS nsegment_le.
func (x *Nsegment) Le(ns2 *Nsegment) (bool, error) {
	_r0, _err := functions.NsegmentLe(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS nsegment_lt.
func (x *Nsegment) Lt(ns2 *Nsegment) (bool, error) {
	_r0, _err := functions.NsegmentLt(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS nsegment_ne.
func (x *Nsegment) Ne(ns2 *Nsegment) (bool, error) {
	_r0, _err := functions.NsegmentNe(functions.NsegmentFromPointer(x.Pointer()), functions.NsegmentFromPointer(ns2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}
