package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Pcpatch struct {
	Value
}

// PcpatchFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func PcpatchFromPointer(p unsafe.Pointer) *Pcpatch {
	if p == nil {
		return nil
	}
	v := &Pcpatch{}
	v.ptr = p
	return v
}

// PcpatchHexIn is MEOS pcpatch_hex_in.
func PcpatchHexIn(str string) (*Pcpatch, error) {
	_r0, _err := functions.PcpatchHexIn(str)
	if _err != nil {
		return nil, _err
	}
	return PcpatchFromPointer(_r0.Pointer()), nil
}

// HexOut is MEOS pcpatch_hex_out.
func (x *Pcpatch) HexOut(maxdd int) (string, error) {
	_r0, _err := functions.PcpatchHexOut(functions.PcpatchFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PcpatchFromHEXWKB is MEOS pcpatch_from_hexwkb.
func PcpatchFromHEXWKB(hexwkb string) (*Pcpatch, error) {
	_r0, _err := functions.PcpatchFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return PcpatchFromPointer(_r0.Pointer()), nil
}

// AsHEXWKB is MEOS pcpatch_as_hexwkb.
func (x *Pcpatch) AsHEXWKB() (string, error) {
	_r0, _err := functions.PcpatchAsHexwkb(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PcpatchMake is MEOS pcpatch_make.
func PcpatchMake(points unsafe.Pointer, count int) (*Pcpatch, error) {
	_r0, _err := functions.PcpatchMake(points, count)
	if _err != nil {
		return nil, _err
	}
	return PcpatchFromPointer(_r0.Pointer()), nil
}

// PcpatchMakeCoords is MEOS pcpatch_make_coords.
func PcpatchMakeCoords(pcid uint32, values unsafe.Pointer, count int) (*Pcpatch, error) {
	_r0, _err := functions.PcpatchMakeCoords(pcid, values, count)
	if _err != nil {
		return nil, _err
	}
	return PcpatchFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS pcpatch_copy.
func (x *Pcpatch) Copy() (*Pcpatch, error) {
	_r0, _err := functions.PcpatchCopy(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PcpatchFromPointer(_r0.Pointer()), nil
}

// GetPcid is MEOS pcpatch_get_pcid.
func (x *Pcpatch) GetPcid() (uint32, error) {
	_r0, _err := functions.PcpatchGetPcid(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Npoints is MEOS pcpatch_npoints.
func (x *Pcpatch) Npoints() (uint32, error) {
	_r0, _err := functions.PcpatchNpoints(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PointN is MEOS pcpatch_point_n.
func (x *Pcpatch) PointN(n int) (*Pcpoint, error) {
	_r0, _err := functions.PcpatchPointN(functions.PcpatchFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, _err
	}
	return PcpointFromPointer(_r0.Pointer()), nil
}

// Points is MEOS pcpatch_points.
func (x *Pcpatch) Points(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PcpatchPoints(functions.PcpatchFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Hash is MEOS pcpatch_hash.
func (x *Pcpatch) Hash() (uint32, error) {
	_r0, _err := functions.PcpatchHash(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS pcpatch_hash_extended.
func (x *Pcpatch) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.PcpatchHashExtended(functions.PcpatchFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToGeom is MEOS pcpatch_to_geom.
func (x *Pcpatch) ToGeom() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.PcpatchToGeom(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS pcpatch_cmp.
func (x *Pcpatch) Cmp(pa2 *Pcpatch) (int, error) {
	_r0, _err := functions.PcpatchCmp(functions.PcpatchFromPointer(x.Pointer()), functions.PcpatchFromPointer(pa2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToSet is MEOS pcpatch_to_set.
func (x *Pcpatch) ToSet() (*Set, error) {
	_r0, _err := functions.PcpatchToSet(functions.PcpatchFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToTpcbox is MEOS pcpatch_to_tpcbox.
func (x *Pcpatch) ToTpcbox(srid int32) (*TPCBox, error) {
	_r0, _err := functions.PcpatchToTpcbox(functions.PcpatchFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}
