package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Pcpoint struct {
	Value
}

// PcpointFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func PcpointFromPointer(p unsafe.Pointer) *Pcpoint {
	if p == nil {
		return nil
	}
	v := &Pcpoint{}
	v.ptr = p
	return v
}

// PcpointHexIn is MEOS pcpoint_hex_in.
func PcpointHexIn(str string) (*Pcpoint, error) {
	_r0, _err := functions.PcpointHexIn(str)
	if _err != nil {
		return nil, _err
	}
	return PcpointFromPointer(_r0.Pointer()), nil
}

// HexOut is MEOS pcpoint_hex_out.
func (x *Pcpoint) HexOut(maxdd int) (string, error) {
	_r0, _err := functions.PcpointHexOut(functions.PcpointFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PcpointFromHEXWKB is MEOS pcpoint_from_hexwkb.
func PcpointFromHEXWKB(hexwkb string) (*Pcpoint, error) {
	_r0, _err := functions.PcpointFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return PcpointFromPointer(_r0.Pointer()), nil
}

// AsHEXWKB is MEOS pcpoint_as_hexwkb.
func (x *Pcpoint) AsHEXWKB() (string, error) {
	_r0, _err := functions.PcpointAsHexwkb(functions.PcpointFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PcpointMake is MEOS pcpoint_make.
func PcpointMake(pcid uint32, values unsafe.Pointer, count int) (*Pcpoint, error) {
	_r0, _err := functions.PcpointMake(pcid, values, count)
	if _err != nil {
		return nil, _err
	}
	return PcpointFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS pcpoint_copy.
func (x *Pcpoint) Copy() (*Pcpoint, error) {
	_r0, _err := functions.PcpointCopy(functions.PcpointFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PcpointFromPointer(_r0.Pointer()), nil
}

// GetPcid is MEOS pcpoint_get_pcid.
func (x *Pcpoint) GetPcid() (uint32, error) {
	_r0, _err := functions.PcpointGetPcid(functions.PcpointFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Hash is MEOS pcpoint_hash.
func (x *Pcpoint) Hash() (uint32, error) {
	_r0, _err := functions.PcpointHash(functions.PcpointFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS pcpoint_hash_extended.
func (x *Pcpoint) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.PcpointHashExtended(functions.PcpointFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// GetX is MEOS pcpoint_get_x.
func (x *Pcpoint) GetX(schema *Pcschema, out unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PcpointGetX(functions.PcpointFromPointer(x.Pointer()), functions.PCSchemaFromPointer(schema.Pointer()), out)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GetY is MEOS pcpoint_get_y.
func (x *Pcpoint) GetY(schema *Pcschema, out unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PcpointGetY(functions.PcpointFromPointer(x.Pointer()), functions.PCSchemaFromPointer(schema.Pointer()), out)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GetZ is MEOS pcpoint_get_z.
func (x *Pcpoint) GetZ(schema *Pcschema, out unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PcpointGetZ(functions.PcpointFromPointer(x.Pointer()), functions.PCSchemaFromPointer(schema.Pointer()), out)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// GetDim is MEOS pcpoint_get_dim.
func (x *Pcpoint) GetDim(schema *Pcschema, name string, out unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PcpointGetDim(functions.PcpointFromPointer(x.Pointer()), functions.PCSchemaFromPointer(schema.Pointer()), name, out)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ToTpcbox is MEOS pcpoint_to_tpcbox.
func (x *Pcpoint) ToTpcbox(schema *Pcschema) (*TPCBox, error) {
	_r0, _err := functions.PcpointToTpcbox(functions.PcpointFromPointer(x.Pointer()), functions.PCSchemaFromPointer(schema.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS pcpoint_cmp.
func (x *Pcpoint) Cmp(pt2 *Pcpoint) (int, error) {
	_r0, _err := functions.PcpointCmp(functions.PcpointFromPointer(x.Pointer()), functions.PcpointFromPointer(pt2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToSet is MEOS pcpoint_to_set.
func (x *Pcpoint) ToSet() (*Set, error) {
	_r0, _err := functions.PcpointToSet(functions.PcpointFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
