package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Pcschema struct {
	Value
}

// PcschemaFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func PcschemaFromPointer(p unsafe.Pointer) *Pcschema {
	if p == nil {
		return nil
	}
	v := &Pcschema{}
	v.ptr = p
	return v
}

// PcschemaGet is MEOS meos_pc_schema.
func PcschemaGet(pcid uint32) (*Pcschema, error) {
	_r0, _err := functions.MeosPcSchema(pcid)
	if _err != nil {
		return nil, _err
	}
	return PcschemaFromPointer(_r0.Pointer()), nil
}

// PcschemaRegister is MEOS meos_pc_schema_register.
func PcschemaRegister(pcid uint32, schema *Pcschema) error {
	return functions.MeosPcSchemaRegister(pcid, functions.PCSchemaFromPointer(schema.Pointer()))
}

// PcschemaFromDims is MEOS meos_pc_schema_from_dims.
func PcschemaFromDims(pcid uint32, srid int32, compression string, dims unsafe.Pointer, ndims int) (*Pcschema, error) {
	_r0, _err := functions.MeosPcSchemaFromDims(pcid, srid, compression, dims, ndims)
	if _err != nil {
		return nil, _err
	}
	return PcschemaFromPointer(_r0.Pointer()), nil
}

// PcschemaRegisterDims is MEOS meos_pc_schema_register_dims.
func PcschemaRegisterDims(pcid uint32, srid int32, compression string, dims unsafe.Pointer, ndims int) (bool, error) {
	_r0, _err := functions.MeosPcSchemaRegisterDims(pcid, srid, compression, dims, ndims)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PcschemaRegisterXml is MEOS meos_pc_schema_register_xml.
func PcschemaRegisterXml(pcid uint32, schema *Pcschema, xml_text string) error {
	return functions.MeosPcSchemaRegisterXml(pcid, functions.PCSchemaFromPointer(schema.Pointer()), xml_text)
}

// PcschemaXml is MEOS meos_pc_schema_xml.
func PcschemaXml(pcid uint32) (string, error) {
	_r0, _err := functions.MeosPcSchemaXml(pcid)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PcschemaClear is MEOS meos_pc_schema_clear.
func PcschemaClear() error {
	return functions.MeosPcSchemaClear()
}

// PcschemaSRID is MEOS meos_pc_schema_srid.
func PcschemaSRID(pcid uint32) (int32, error) {
	_r0, _err := functions.MeosPcSchemaSRID(pcid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PcschemaCompression is MEOS meos_pc_schema_compression.
func PcschemaCompression(pcid uint32) (string, error) {
	_r0, _err := functions.MeosPcSchemaCompression(pcid)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PcschemaNdims is MEOS meos_pc_schema_ndims.
func PcschemaNdims(pcid uint32) (int32, error) {
	_r0, _err := functions.MeosPcSchemaNdims(pcid)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}
