package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Pose struct {
	Value
}

// PoseFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func PoseFromPointer(p unsafe.Pointer) *Pose {
	if p == nil {
		return nil
	}
	v := &Pose{}
	v.ptr = p
	return v
}

// AsEWKT is MEOS pose_as_ewkt.
func (x *Pose) AsEWKT(maxdd int) (string, error) {
	_r0, _err := functions.PoseAsEWKT(functions.PoseFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsHEXWKB is MEOS pose_as_hexwkb.
func (x *Pose) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.PoseAsHexwkb(functions.PoseFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsText is MEOS pose_as_text.
func (x *Pose) AsText(maxdd int) (string, error) {
	_r0, _err := functions.PoseAsText(functions.PoseFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS pose_as_wkb.
func (x *Pose) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PoseAsWKB(functions.PoseFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseFromWKB is MEOS pose_from_wkb.
func PoseFromWKB(wkb unsafe.Pointer, size uint) (*Pose, error) {
	_r0, _err := functions.PoseFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseFromHEXWKB is MEOS pose_from_hexwkb.
func PoseFromHEXWKB(hexwkb string) (*Pose, error) {
	_r0, _err := functions.PoseFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseIn is MEOS pose_in.
func PoseIn(str string) (*Pose, error) {
	_r0, _err := functions.PoseIn(str)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// Out is MEOS pose_out.
func (x *Pose) Out(maxdd int) (string, error) {
	_r0, _err := functions.PoseOut(functions.PoseFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PoseFromGeopose is MEOS pose_from_geopose.
func PoseFromGeopose(json string) (*Pose, error) {
	_r0, _err := functions.PoseFromGeopose(json)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// AsGeopose is MEOS pose_as_geopose.
func (x *Pose) AsGeopose(conformance int, precision int) (string, error) {
	_r0, _err := functions.PoseAsGeopose(functions.PoseFromPointer(x.Pointer()), conformance, precision)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ApplyGeo is MEOS pose_apply_geo.
func (x *Pose) ApplyGeo(body *TRGeometrySeqSet) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.PoseApplyGeo(functions.PoseFromPointer(x.Pointer()), functions.GeomFromPointer(body.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ComposeTpose is MEOS pose_compose_tpose.
func (x *Pose) ComposeTpose(frame *Temporal) (*Temporal, error) {
	_r0, _err := functions.PoseComposeTpose(functions.PoseFromPointer(x.Pointer()), functions.TemporalFromPointer(frame.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS pose_copy.
func (x *Pose) Copy() (*Pose, error) {
	_r0, _err := functions.PoseCopy(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseMake2d is MEOS pose_make_2d.
func PoseMake2d(x float64, y float64, theta float64, geodetic bool, srid int32) (*Pose, error) {
	_r0, _err := functions.PoseMake2d(x, y, theta, geodetic, srid)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseMake3d is MEOS pose_make_3d.
func PoseMake3d(x float64, y float64, z float64, W float64, X float64, Y float64, Z float64, geodetic bool, srid int32) (*Pose, error) {
	_r0, _err := functions.PoseMake3d(x, y, z, W, X, Y, Z, geodetic, srid)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseMakePoint2d is MEOS pose_make_point2d.
func PoseMakePoint2d(gs *TRGeometrySeqSet, theta float64) (*Pose, error) {
	_r0, _err := functions.PoseMakePoint2d(functions.GeomFromPointer(gs.Pointer()), theta)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseMakePoint3d is MEOS pose_make_point3d.
func PoseMakePoint3d(gs *TRGeometrySeqSet, W float64, X float64, Y float64, Z float64) (*Pose, error) {
	_r0, _err := functions.PoseMakePoint3d(functions.GeomFromPointer(gs.Pointer()), W, X, Y, Z)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseMakePoint3dYpr is MEOS pose_make_point3d_ypr.
func PoseMakePoint3dYpr(gs *TRGeometrySeqSet, yaw float64, pitch float64, roll float64) (*Pose, error) {
	_r0, _err := functions.PoseMakePoint3dYpr(functions.GeomFromPointer(gs.Pointer()), yaw, pitch, roll)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// ToPoint is MEOS pose_to_point.
func (x *Pose) ToPoint() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.PoseToPoint(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ToStbox is MEOS pose_to_stbox.
func (x *Pose) ToStbox() (*STBox, error) {
	_r0, _err := functions.PoseToSTBOX(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS pose_hash.
func (x *Pose) Hash() (uint32, error) {
	_r0, _err := functions.PoseHash(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS pose_hash_extended.
func (x *Pose) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.PoseHashExtended(functions.PoseFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Quaternion is MEOS pose_quaternion.
func (x *Pose) Quaternion(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PoseQuaternion(functions.PoseFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Ypr is MEOS pose_ypr.
func (x *Pose) Ypr(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PoseYpr(functions.PoseFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Yaw is MEOS pose_yaw.
func (x *Pose) Yaw() (float64, error) {
	_r0, _err := functions.PoseYaw(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Pitch is MEOS pose_pitch.
func (x *Pose) Pitch() (float64, error) {
	_r0, _err := functions.PosePitch(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Roll is MEOS pose_roll.
func (x *Pose) Roll() (float64, error) {
	_r0, _err := functions.PoseRoll(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// AngularDistance is MEOS pose_angular_distance.
func (x *Pose) AngularDistance(pose2 *Pose) (float64, error) {
	_r0, _err := functions.PoseAngularDistance(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Compose is MEOS pose_compose.
func (x *Pose) Compose(frame *Pose) (*Pose, error) {
	_r0, _err := functions.PoseCompose(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(frame.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// Inverse is MEOS pose_inverse.
func (x *Pose) Inverse() (*Pose, error) {
	_r0, _err := functions.PoseInverse(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// Normalize is MEOS pose_normalize.
func (x *Pose) Normalize() (*Pose, error) {
	_r0, _err := functions.PoseNormalize(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// Round is MEOS pose_round.
func (x *Pose) Round(maxdd int) (*Pose, error) {
	_r0, _err := functions.PoseRound(functions.PoseFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// SetSRID is MEOS pose_set_srid.
func (x *Pose) SetSRID(srid int32) (*Pose, error) {
	_r0, _err := functions.PoseSetSRID(functions.PoseFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// SRID is MEOS pose_srid.
func (x *Pose) SRID() (int32, error) {
	_r0, _err := functions.PoseSRID(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Transform is MEOS pose_transform.
func (x *Pose) Transform(srid int32) (*Pose, error) {
	_r0, _err := functions.PoseTransform(functions.PoseFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// TransformPipeline is MEOS pose_transform_pipeline.
func (x *Pose) TransformPipeline(pipelinestr string, srid int32, is_forward bool) (*Pose, error) {
	_r0, _err := functions.PoseTransformPipeline(functions.PoseFromPointer(x.Pointer()), pipelinestr, srid, is_forward)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// TstzspanToStbox is MEOS pose_tstzspan_to_stbox.
func (x *Pose) TstzspanToStbox(s *Span) (*STBox, error) {
	_r0, _err := functions.PoseTstzspanToSTBOX(functions.PoseFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// TimestamptzToStbox is MEOS pose_timestamptz_to_stbox.
func (x *Pose) TimestamptzToStbox(t int64) (*STBox, error) {
	_r0, _err := functions.PoseTimestamptzToSTBOX(functions.PoseFromPointer(x.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS pose_cmp.
func (x *Pose) Cmp(pose2 *Pose) (int, error) {
	_r0, _err := functions.PoseCmp(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS pose_eq.
func (x *Pose) Eq(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseEq(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS pose_ge.
func (x *Pose) Ge(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseGe(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS pose_gt.
func (x *Pose) Gt(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseGt(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS pose_le.
func (x *Pose) Le(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseLe(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS pose_lt.
func (x *Pose) Lt(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseLt(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS pose_ne.
func (x *Pose) Ne(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseNe(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Nsame is MEOS pose_nsame.
func (x *Pose) Nsame(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseNsame(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Same is MEOS pose_same.
func (x *Pose) Same(pose2 *Pose) (bool, error) {
	_r0, _err := functions.PoseSame(functions.PoseFromPointer(x.Pointer()), functions.PoseFromPointer(pose2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ToSet is MEOS pose_to_set.
func (x *Pose) ToSet() (*Set, error) {
	_r0, _err := functions.PoseToSet(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToPosechain is MEOS pose_to_posechain.
func (x *Pose) ToPosechain() (unsafe.Pointer, error) {
	_r0, _err := functions.PoseToPosechain(functions.PoseFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
