package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type PoseSet struct {
	Set
}

// PoseSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func PoseSetFromPointer(p unsafe.Pointer) *PoseSet {
	if p == nil {
		return nil
	}
	v := &PoseSet{}
	v.ptr = p
	return v
}

// PoseSetIn is MEOS poseset_in.
func PoseSetIn(str string) (*Set, error) {
	_r0, _err := functions.PosesetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS poseset_out.
func (x *PoseSet) Out(maxdd int) (string, error) {
	_r0, _err := functions.PosesetOut(functions.SetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PoseSetMake is MEOS poseset_make.
func PoseSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.PosesetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS poseset_end_value.
func (x *PoseSet) EndValue() (*Pose, error) {
	_r0, _err := functions.PosesetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS poseset_start_value.
func (x *PoseSet) StartValue() (*Pose, error) {
	_r0, _err := functions.PosesetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// ValueN is MEOS poseset_value_n.
func (x *PoseSet) ValueN(n int) (*Pose, bool, error) {
	_found, _value, _err := functions.PosesetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return PoseFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS poseset_values.
func (x *PoseSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PosesetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}
