package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type PoseChain struct {
	Value
}

// PoseChainFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func PoseChainFromPointer(p unsafe.Pointer) *PoseChain {
	if p == nil {
		return nil
	}
	v := &PoseChain{}
	v.ptr = p
	return v
}

// PoseChainIn is MEOS posechain_in.
func PoseChainIn(str string) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainIn(str)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainOut is MEOS posechain_out.
func PoseChainOut(pc unsafe.Pointer, maxdd int) (string, error) {
	_r0, _err := functions.PosechainOut(pc, maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PoseChainAsText is MEOS posechain_as_text.
func PoseChainAsText(pc unsafe.Pointer, maxdd int) (string, error) {
	_r0, _err := functions.PosechainAsText(pc, maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PoseChainAsEWKT is MEOS posechain_as_ewkt.
func PoseChainAsEWKT(pc unsafe.Pointer, maxdd int) (string, error) {
	_r0, _err := functions.PosechainAsEWKT(pc, maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PoseChainAsWKB is MEOS posechain_as_wkb.
func PoseChainAsWKB(pc unsafe.Pointer, variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainAsWKB(pc, variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainAsHEXWKB is MEOS posechain_as_hexwkb.
func PoseChainAsHEXWKB(pc unsafe.Pointer, variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.PosechainAsHexwkb(pc, variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// PoseChainFromWKB is MEOS posechain_from_wkb.
func PoseChainFromWKB(wkb unsafe.Pointer, size uint) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainFromHEXWKB is MEOS posechain_from_hexwkb.
func PoseChainFromHEXWKB(hexwkb string) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainMake is MEOS posechain_make.
func PoseChainMake(poses unsafe.Pointer, count int) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainMake(poses, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainCopy is MEOS posechain_copy.
func PoseChainCopy(pc unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainCopy(pc)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainAppend is MEOS posechain_append.
func PoseChainAppend(pc unsafe.Pointer, pose *Pose) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainAppend(pc, functions.PoseFromPointer(pose.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainToPose is MEOS posechain_to_pose.
func PoseChainToPose(pc unsafe.Pointer) (*Pose, error) {
	_r0, _err := functions.PosechainToPose(pc)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseChainPrefixPose is MEOS posechain_prefix_pose.
func PoseChainPrefixPose(pc unsafe.Pointer, n int) (*Pose, error) {
	_r0, _err := functions.PosechainPrefixPose(pc, n)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseChainToPoint is MEOS posechain_to_point.
func PoseChainToPoint(pc unsafe.Pointer) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.PosechainToPoint(pc)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// PoseChainToStbox is MEOS posechain_to_stbox.
func PoseChainToStbox(pc unsafe.Pointer) (*STBox, error) {
	_r0, _err := functions.PosechainToSTBOX(pc)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// PoseChainTimestamptzToStbox is MEOS posechain_timestamptz_to_stbox.
func PoseChainTimestamptzToStbox(pc unsafe.Pointer, t int64) (*STBox, error) {
	_r0, _err := functions.PosechainTimestamptzToSTBOX(pc, t)
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// PoseChainTstzspanToStbox is MEOS posechain_tstzspan_to_stbox.
func PoseChainTstzspanToStbox(pc unsafe.Pointer, s *Span) (*STBox, error) {
	_r0, _err := functions.PosechainTstzspanToSTBOX(pc, functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// PoseChainNumPoses is MEOS posechain_num_poses.
func PoseChainNumPoses(pc unsafe.Pointer) (int, error) {
	_r0, _err := functions.PosechainNumPoses(pc)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PoseChainStartPose is MEOS posechain_start_pose.
func PoseChainStartPose(pc unsafe.Pointer) (*Pose, error) {
	_r0, _err := functions.PosechainStartPose(pc)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseChainEndPose is MEOS posechain_end_pose.
func PoseChainEndPose(pc unsafe.Pointer) (*Pose, error) {
	_r0, _err := functions.PosechainEndPose(pc)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseChainPoseN is MEOS posechain_pose_n.
func PoseChainPoseN(pc unsafe.Pointer, n int) (*Pose, error) {
	_r0, _err := functions.PosechainPoseN(pc, n)
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// PoseChainPoses is MEOS posechain_poses.
func PoseChainPoses(pc unsafe.Pointer, count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainPoses(pc, count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainHash is MEOS posechain_hash.
func PoseChainHash(pc unsafe.Pointer) (uint32, error) {
	_r0, _err := functions.PosechainHash(pc)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PoseChainHashExtended is MEOS posechain_hash_extended.
func PoseChainHashExtended(pc unsafe.Pointer, seed uint64) (uint64, error) {
	_r0, _err := functions.PosechainHashExtended(pc, seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PoseChainRound is MEOS posechain_round.
func PoseChainRound(pc unsafe.Pointer, maxdd int) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainRound(pc, maxdd)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainSRID is MEOS posechain_srid.
func PoseChainSRID(pc unsafe.Pointer) (int32, error) {
	_r0, _err := functions.PosechainSRID(pc)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PoseChainSetSRID is MEOS posechain_set_srid.
func PoseChainSetSRID(pc unsafe.Pointer, srid int32) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainSetSRID(pc, srid)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainTransform is MEOS posechain_transform.
func PoseChainTransform(pc unsafe.Pointer, srid_to int32) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainTransform(pc, srid_to)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainTransformPipeline is MEOS posechain_transform_pipeline.
func PoseChainTransformPipeline(pc unsafe.Pointer, pipeline string, srid_to int32, is_forward bool) (unsafe.Pointer, error) {
	_r0, _err := functions.PosechainTransformPipeline(pc, pipeline, srid_to, is_forward)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// PoseChainEq is MEOS posechain_eq.
func PoseChainEq(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainEq(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainNe is MEOS posechain_ne.
func PoseChainNe(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainNe(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainSame is MEOS posechain_same.
func PoseChainSame(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainSame(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainNsame is MEOS posechain_nsame.
func PoseChainNsame(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainNsame(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainCmp is MEOS posechain_cmp.
func PoseChainCmp(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (int, error) {
	_r0, _err := functions.PosechainCmp(pc1, pc2)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// PoseChainLt is MEOS posechain_lt.
func PoseChainLt(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainLt(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainLe is MEOS posechain_le.
func PoseChainLe(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainLe(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainGt is MEOS posechain_gt.
func PoseChainGt(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainGt(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainGe is MEOS posechain_ge.
func PoseChainGe(pc1 unsafe.Pointer, pc2 unsafe.Pointer) (bool, error) {
	_r0, _err := functions.PosechainGe(pc1, pc2)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// PoseChainToSet is MEOS posechain_to_set.
func PoseChainToSet(pc unsafe.Pointer) (*Set, error) {
	_r0, _err := functions.PosechainToSet(pc)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
