package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type Raquet struct {
	Value
}

// RaquetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func RaquetFromPointer(p unsafe.Pointer) *Raquet {
	if p == nil {
		return nil
	}
	v := &Raquet{}
	v.ptr = p
	return v
}
