package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type RTreeNNCursor struct {
	Value
}

// RTreeNNCursorFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func RTreeNNCursorFromPointer(p unsafe.Pointer) *RTreeNNCursor {
	if p == nil {
		return nil
	}
	v := &RTreeNNCursor{}
	v.ptr = p
	return v
}

// RTreeNNCursorOpen is MEOS rtree_nn_cursor_open.
func RTreeNNCursorOpen(rtree *RTree, query unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.RtreeNnCursorOpen(functions.RTreeFromPointer(rtree.Pointer()), query)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// RTreeNNCursorNext is MEOS rtree_nn_cursor_next.
func RTreeNNCursorNext(cursor unsafe.Pointer, id_out unsafe.Pointer, dist_out unsafe.Pointer) (bool, error) {
	_r0, _err := functions.RtreeNnCursorNext(cursor, id_out, dist_out)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// RTreeNNCursorClose is MEOS rtree_nn_cursor_close.
func RTreeNNCursorClose(cursor unsafe.Pointer) error {
	return functions.RtreeNnCursorClose(cursor)
}
