package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Set struct {
	Collection
}

// SetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func SetFromPointer(p unsafe.Pointer) *Set {
	if p == nil {
		return nil
	}
	v := &Set{}
	v.ptr = p
	return v
}

// AsHEXWKB is MEOS set_as_hexwkb.
func (x *Set) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.SetAsHexwkb(functions.SetFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS set_as_wkb.
func (x *Set) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.SetAsWKB(functions.SetFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// SetFromHEXWKB is MEOS set_from_hexwkb.
func SetFromHEXWKB(hexwkb string) (*Set, error) {
	_r0, _err := functions.SetFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// SetFromWKB is MEOS set_from_wkb.
func SetFromWKB(wkb unsafe.Pointer, size uint) (*Set, error) {
	_r0, _err := functions.SetFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS set_copy.
func (x *Set) Copy() (*Set, error) {
	_r0, _err := functions.SetCopy(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// ToSpan is MEOS set_to_span.
func (x *Set) ToSpan() (*Span, error) {
	_r0, _err := functions.SetToSpan(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToSpanset is MEOS set_to_spanset.
func (x *Set) ToSpanset() (*SpanSet, error) {
	_r0, _err := functions.SetToSpanset(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS set_hash.
func (x *Set) Hash() (uint32, error) {
	_r0, _err := functions.SetHash(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS set_hash_extended.
func (x *Set) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.SetHashExtended(functions.SetFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// NumValues is MEOS set_num_values.
func (x *Set) NumValues() (int, error) {
	_r0, _err := functions.SetNumValues(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Round is MEOS set_round.
func (x *Set) Round(maxdd int) (*Set, error) {
	_r0, _err := functions.SetRound(functions.SetFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS set_cmp.
func (x *Set) Cmp(s2 *Set) (int, error) {
	_r0, _err := functions.SetCmp(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS set_eq.
func (x *Set) Eq(s2 *Set) (bool, error) {
	_r0, _err := functions.SetEq(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS set_ge.
func (x *Set) Ge(s2 *Set) (bool, error) {
	_r0, _err := functions.SetGe(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS set_gt.
func (x *Set) Gt(s2 *Set) (bool, error) {
	_r0, _err := functions.SetGt(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS set_le.
func (x *Set) Le(s2 *Set) (bool, error) {
	_r0, _err := functions.SetLe(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS set_lt.
func (x *Set) Lt(s2 *Set) (bool, error) {
	_r0, _err := functions.SetLt(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS set_ne.
func (x *Set) Ne(s2 *Set) (bool, error) {
	_r0, _err := functions.SetNe(functions.SetFromPointer(x.Pointer()), functions.SetFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Spans is MEOS set_spans.
func (x *Set) Spans(count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.SetSpans(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SplitEachNSpans is MEOS set_split_each_n_spans.
func (x *Set) SplitEachNSpans(elems_per_span int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.SetSplitEachNSpans(functions.SetFromPointer(x.Pointer()), elems_per_span, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SplitNSpans is MEOS set_split_n_spans.
func (x *Set) SplitNSpans(span_count int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.SetSplitNSpans(functions.SetFromPointer(x.Pointer()), span_count, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToTbox is MEOS set_to_tbox.
func (x *Set) ToTbox() (*TBox, error) {
	_r0, _err := functions.SetToTBOX(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}
