package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Span struct {
	Collection
}

// SpanFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func SpanFromPointer(p unsafe.Pointer) *Span {
	if p == nil {
		return nil
	}
	v := &Span{}
	v.ptr = p
	return v
}

// AsHEXWKB is MEOS span_as_hexwkb.
func (x *Span) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.SpanAsHexwkb(functions.SpanFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS span_as_wkb.
func (x *Span) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.SpanAsWKB(functions.SpanFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// SpanFromHEXWKB is MEOS span_from_hexwkb.
func SpanFromHEXWKB(hexwkb string) (*Span, error) {
	_r0, _err := functions.SpanFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SpanFromWKB is MEOS span_from_wkb.
func SpanFromWKB(wkb unsafe.Pointer, size uint) (*Span, error) {
	_r0, _err := functions.SpanFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS span_copy.
func (x *Span) Copy() (*Span, error) {
	_r0, _err := functions.SpanCopy(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToSpanset is MEOS span_to_spanset.
func (x *Span) ToSpanset() (*SpanSet, error) {
	_r0, _err := functions.SpanToSpanset(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS span_hash.
func (x *Span) Hash() (uint32, error) {
	_r0, _err := functions.SpanHash(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS span_hash_extended.
func (x *Span) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.SpanHashExtended(functions.SpanFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// LowerInc is MEOS span_lower_inc.
func (x *Span) LowerInc() (bool, error) {
	_r0, _err := functions.SpanLowerInc(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// UpperInc is MEOS span_upper_inc.
func (x *Span) UpperInc() (bool, error) {
	_r0, _err := functions.SpanUpperInc(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Cmp is MEOS span_cmp.
func (x *Span) Cmp(s2 *Span) (int, error) {
	_r0, _err := functions.SpanCmp(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS span_eq.
func (x *Span) Eq(s2 *Span) (bool, error) {
	_r0, _err := functions.SpanEq(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS span_ge.
func (x *Span) Ge(s2 *Span) (bool, error) {
	_r0, _err := functions.SpanGe(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS span_gt.
func (x *Span) Gt(s2 *Span) (bool, error) {
	_r0, _err := functions.SpanGt(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS span_le.
func (x *Span) Le(s2 *Span) (bool, error) {
	_r0, _err := functions.SpanLe(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS span_lt.
func (x *Span) Lt(s2 *Span) (bool, error) {
	_r0, _err := functions.SpanLt(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS span_ne.
func (x *Span) Ne(s2 *Span) (bool, error) {
	_r0, _err := functions.SpanNe(functions.SpanFromPointer(x.Pointer()), functions.SpanFromPointer(s2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ToTbox is MEOS span_to_tbox.
func (x *Span) ToTbox() (*TBox, error) {
	_r0, _err := functions.SpanToTBOX(functions.SpanFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}
