package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type SpanSet struct {
	Collection
}

// SpanSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func SpanSetFromPointer(p unsafe.Pointer) *SpanSet {
	if p == nil {
		return nil
	}
	v := &SpanSet{}
	v.ptr = p
	return v
}

// AsHEXWKB is MEOS spanset_as_hexwkb.
func (x *SpanSet) AsHEXWKB(variant uint8, size_out unsafe.Pointer) (string, error) {
	_r0, _err := functions.SpansetAsHexwkb(functions.SpanSetFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsWKB is MEOS spanset_as_wkb.
func (x *SpanSet) AsWKB(variant uint8, size_out unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.SpansetAsWKB(functions.SpanSetFromPointer(x.Pointer()), variant, size_out)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// SpanSetFromHEXWKB is MEOS spanset_from_hexwkb.
func SpanSetFromHEXWKB(hexwkb string) (*SpanSet, error) {
	_r0, _err := functions.SpansetFromHexwkb(hexwkb)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// SpanSetFromWKB is MEOS spanset_from_wkb.
func SpanSetFromWKB(wkb unsafe.Pointer, size uint) (*SpanSet, error) {
	_r0, _err := functions.SpansetFromWKB(wkb, size)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS spanset_copy.
func (x *SpanSet) Copy() (*SpanSet, error) {
	_r0, _err := functions.SpansetCopy(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// SpanSetMake is MEOS spanset_make.
func SpanSetMake(spans *Span, count int) (*SpanSet, error) {
	_r0, _err := functions.SpansetMake(functions.SpanFromPointer(spans.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// EndSpan is MEOS spanset_end_span.
func (x *SpanSet) EndSpan() (*Span, error) {
	_r0, _err := functions.SpansetEndSpan(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Hash is MEOS spanset_hash.
func (x *SpanSet) Hash() (uint32, error) {
	_r0, _err := functions.SpansetHash(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// HashExtended is MEOS spanset_hash_extended.
func (x *SpanSet) HashExtended(seed uint64) (uint64, error) {
	_r0, _err := functions.SpansetHashExtended(functions.SpanSetFromPointer(x.Pointer()), seed)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// LowerInc is MEOS spanset_lower_inc.
func (x *SpanSet) LowerInc() (bool, error) {
	_r0, _err := functions.SpansetLowerInc(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// NumSpans is MEOS spanset_num_spans.
func (x *SpanSet) NumSpans() (int, error) {
	_r0, _err := functions.SpansetNumSpans(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Span is MEOS spanset_span.
func (x *SpanSet) Span() (*Span, error) {
	_r0, _err := functions.SpansetSpan(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SpanN is MEOS spanset_span_n.
func (x *SpanSet) SpanN(i int) (*Span, error) {
	_r0, _err := functions.SpansetSpanN(functions.SpanSetFromPointer(x.Pointer()), i)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// Spanarr is MEOS spanset_spanarr.
func (x *SpanSet) Spanarr(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.SpansetSpanarr(functions.SpanSetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// StartSpan is MEOS spanset_start_span.
func (x *SpanSet) StartSpan() (*Span, error) {
	_r0, _err := functions.SpansetStartSpan(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// UpperInc is MEOS spanset_upper_inc.
func (x *SpanSet) UpperInc() (bool, error) {
	_r0, _err := functions.SpansetUpperInc(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Cmp is MEOS spanset_cmp.
func (x *SpanSet) Cmp(ss2 *SpanSet) (int, error) {
	_r0, _err := functions.SpansetCmp(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS spanset_eq.
func (x *SpanSet) Eq(ss2 *SpanSet) (bool, error) {
	_r0, _err := functions.SpansetEq(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS spanset_ge.
func (x *SpanSet) Ge(ss2 *SpanSet) (bool, error) {
	_r0, _err := functions.SpansetGe(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS spanset_gt.
func (x *SpanSet) Gt(ss2 *SpanSet) (bool, error) {
	_r0, _err := functions.SpansetGt(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS spanset_le.
func (x *SpanSet) Le(ss2 *SpanSet) (bool, error) {
	_r0, _err := functions.SpansetLe(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS spanset_lt.
func (x *SpanSet) Lt(ss2 *SpanSet) (bool, error) {
	_r0, _err := functions.SpansetLt(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS spanset_ne.
func (x *SpanSet) Ne(ss2 *SpanSet) (bool, error) {
	_r0, _err := functions.SpansetNe(functions.SpanSetFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Spans is MEOS spanset_spans.
func (x *SpanSet) Spans(count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.SpansetSpans(functions.SpanSetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SplitEachNSpans is MEOS spanset_split_each_n_spans.
func (x *SpanSet) SplitEachNSpans(elems_per_span int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.SpansetSplitEachNSpans(functions.SpanSetFromPointer(x.Pointer()), elems_per_span, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// SplitNSpans is MEOS spanset_split_n_spans.
func (x *SpanSet) SplitNSpans(span_count int, count unsafe.Pointer) (*Span, error) {
	_r0, _err := functions.SpansetSplitNSpans(functions.SpanSetFromPointer(x.Pointer()), span_count, count)
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToTbox is MEOS spanset_to_tbox.
func (x *SpanSet) ToTbox() (*TBox, error) {
	_r0, _err := functions.SpansetToTBOX(functions.SpanSetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}
