package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type SPNNCursor struct {
	Value
}

// SPNNCursorFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func SPNNCursorFromPointer(p unsafe.Pointer) *SPNNCursor {
	if p == nil {
		return nil
	}
	v := &SPNNCursor{}
	v.ptr = p
	return v
}

// SPNNCursorOpen is MEOS sptree_nn_cursor_open.
func SPNNCursorOpen(sptree unsafe.Pointer, query unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.SptreeNnCursorOpen(sptree, query)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// SPNNCursorNext is MEOS sptree_nn_cursor_next.
func SPNNCursorNext(cursor unsafe.Pointer, id_out unsafe.Pointer, dist_out unsafe.Pointer) (bool, error) {
	_r0, _err := functions.SptreeNnCursorNext(cursor, id_out, dist_out)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// SPNNCursorClose is MEOS sptree_nn_cursor_close.
func SPNNCursorClose(cursor unsafe.Pointer) error {
	return functions.SptreeNnCursorClose(cursor)
}
