package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type SPTree struct {
	Value
}

// SPTreeFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func SPTreeFromPointer(p unsafe.Pointer) *SPTree {
	if p == nil {
		return nil
	}
	v := &SPTree{}
	v.ptr = p
	return v
}

// SPTreeFree is MEOS sptree_free.
func SPTreeFree(sptree unsafe.Pointer) error {
	return functions.SptreeFree(sptree)
}

// SPTreeNumEntries is MEOS sptree_num_entries.
func SPTreeNumEntries(sptree unsafe.Pointer) (int, error) {
	_r0, _err := functions.SptreeNumEntries(sptree)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// SPTreeMemSize is MEOS sptree_mem_size.
func SPTreeMemSize(sptree unsafe.Pointer) (int64, error) {
	_r0, _err := functions.SptreeMemSize(sptree)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// SPTreeHeight is MEOS sptree_height.
func SPTreeHeight(sptree unsafe.Pointer) (int, error) {
	_r0, _err := functions.SptreeHeight(sptree)
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// SPTreeInsert is MEOS sptree_insert.
func SPTreeInsert(sptree unsafe.Pointer, box unsafe.Pointer, id int64) (bool, error) {
	_r0, _err := functions.SptreeInsert(sptree, box, id)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// SPTreeLoad is MEOS sptree_load.
func SPTreeLoad(sptree unsafe.Pointer, boxes unsafe.Pointer, ids unsafe.Pointer, count int) (bool, error) {
	_r0, _err := functions.SptreeLoad(sptree, boxes, ids, count)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// SPTreeInsertTemporal is MEOS sptree_insert_temporal.
func SPTreeInsertTemporal(sptree unsafe.Pointer, temp *Temporal, id int64) (bool, error) {
	_r0, _err := functions.SptreeInsertTemporal(sptree, functions.TemporalFromPointer(temp.Pointer()), id)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// SPTreeInsertTemporalSplit is MEOS sptree_insert_temporal_split.
func SPTreeInsertTemporalSplit(sptree unsafe.Pointer, temp *Temporal, id int64, maxboxes int) (bool, error) {
	_r0, _err := functions.SptreeInsertTemporalSplit(sptree, functions.TemporalFromPointer(temp.Pointer()), id, maxboxes)
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}
