package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

// TAlpha is non-numeric, non-spatial temporal types (step/discrete interpolation only). A real MEOS grouping (talpha_type) with no user-facing class name in PyMEOS — see corrections.

type TAlpha struct {
	Temporal
}

// TAlphaFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TAlphaFromPointer(p unsafe.Pointer) *TAlpha {
	if p == nil {
		return nil
	}
	v := &TAlpha{}
	v.ptr = p
	return v
}
