package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBigintSeqSet struct {
	handle
}

// TBigintSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBigintSeqSetFromPointer(p unsafe.Pointer) *TBigintSeqSet {
	if p == nil {
		return nil
	}
	v := &TBigintSeqSet{}
	v.ptr = p
	return v
}

// TBigintSeqSetFromBaseTstzspanset is MEOS tbigintseqset_from_base_tstzspanset.
func TBigintSeqSetFromBaseTstzspanset(i int64, ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TbigintseqsetFromBaseTstzspanset(i, functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
