package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBigintSeq struct {
	handle
}

// TBigintSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBigintSeqFromPointer(p unsafe.Pointer) *TBigintSeq {
	if p == nil {
		return nil
	}
	v := &TBigintSeq{}
	v.ptr = p
	return v
}

// TBigintSeqFromBaseTstzset is MEOS tbigintseq_from_base_tstzset.
func TBigintSeqFromBaseTstzset(i int64, s *Set) (*Temporal, error) {
	_r0, _err := functions.TbigintseqFromBaseTstzset(i, functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TBigintSeqFromBaseTstzspan is MEOS tbigintseq_from_base_tstzspan.
func TBigintSeqFromBaseTstzspan(i int64, s *Span) (*Temporal, error) {
	_r0, _err := functions.TbigintseqFromBaseTstzspan(i, functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
