package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBigint struct {
	TNumber
}

// TBigintFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBigintFromPointer(p unsafe.Pointer) *TBigint {
	if p == nil {
		return nil
	}
	v := &TBigint{}
	v.ptr = p
	return v
}

// TBigintFromMFJSON is MEOS tbigint_from_mfjson.
func TBigintFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TbigintFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TBigintIn is MEOS tbigint_in.
func TBigintIn(str string) (*Temporal, error) {
	_r0, _err := functions.TbigintIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tbigint_out.
func (x *TBigint) Out() (string, error) {
	_r0, _err := functions.TbigintOut(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TBigintFromBaseTemp is MEOS tbigint_from_base_temp.
func TBigintFromBaseTemp(i int64, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TbigintFromBaseTemp(i, functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTint is MEOS tbigint_to_tint.
func (x *TBigint) ToTint() (*Temporal, error) {
	_r0, _err := functions.TbigintToTint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTfloat is MEOS tbigint_to_tfloat.
func (x *TBigint) ToTfloat() (*Temporal, error) {
	_r0, _err := functions.TbigintToTfloat(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tbigint_end_value.
func (x *TBigint) EndValue() (int64, error) {
	_r0, _err := functions.TbigintEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MaxValue is MEOS tbigint_max_value.
func (x *TBigint) MaxValue() (int64, error) {
	_r0, _err := functions.TbigintMaxValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// MinValue is MEOS tbigint_min_value.
func (x *TBigint) MinValue() (int64, error) {
	_r0, _err := functions.TbigintMinValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// StartValue is MEOS tbigint_start_value.
func (x *TBigint) StartValue() (int64, error) {
	_r0, _err := functions.TbigintStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ValueAtTimestamptz is MEOS tbigint_value_at_timestamptz.
func (x *TBigint) ValueAtTimestamptz(t int64, strict bool) (int64, bool, error) {
	_found, _value, _err := functions.TbigintValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// ValueN is MEOS tbigint_value_n.
func (x *TBigint) ValueN(n int64) (int64, bool, error) {
	_found, _value, _err := functions.TbigintValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Values is MEOS tbigint_values.
func (x *TBigint) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TbigintValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ScaleValue is MEOS tbigint_scale_value.
func (x *TBigint) ScaleValue(width int64) (*Temporal, error) {
	_r0, _err := functions.TbigintScaleValue(functions.TemporalFromPointer(x.Pointer()), width)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftScaleValue is MEOS tbigint_shift_scale_value.
func (x *TBigint) ShiftScaleValue(shift int64, width int64) (*Temporal, error) {
	_r0, _err := functions.TbigintShiftScaleValue(functions.TemporalFromPointer(x.Pointer()), shift, width)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ShiftValue is MEOS tbigint_shift_value.
func (x *TBigint) ShiftValue(shift int64) (*Temporal, error) {
	_r0, _err := functions.TbigintShiftValue(functions.TemporalFromPointer(x.Pointer()), shift)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTh3index is MEOS tbigint_to_th3index.
func (x *TBigint) ToTh3index() (*Temporal, error) {
	_r0, _err := functions.TbigintToTh3index(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTquadbin is MEOS tbigint_to_tquadbin.
func (x *TBigint) ToTquadbin() (*Temporal, error) {
	_r0, _err := functions.TbigintToTquadbin(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
