package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBigintInst struct {
	handle
}

// TBigintInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBigintInstFromPointer(p unsafe.Pointer) *TBigintInst {
	if p == nil {
		return nil
	}
	v := &TBigintInst{}
	v.ptr = p
	return v
}

// TBigintInstMake is MEOS tbigintinst_make.
func TBigintInstMake(i int64, t int64) (*Temporal, error) {
	_r0, _err := functions.TbigintinstMake(i, t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
