package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBoolSeqSet struct {
	handle
}

// TBoolSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBoolSeqSetFromPointer(p unsafe.Pointer) *TBoolSeqSet {
	if p == nil {
		return nil
	}
	v := &TBoolSeqSet{}
	v.ptr = p
	return v
}

// TBoolSeqSetFromBaseTstzspanset is MEOS tboolseqset_from_base_tstzspanset.
func TBoolSeqSetFromBaseTstzspanset(b bool, ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TboolseqsetFromBaseTstzspanset(b, functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
