package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBoolInst struct {
	handle
}

// TBoolInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBoolInstFromPointer(p unsafe.Pointer) *TBoolInst {
	if p == nil {
		return nil
	}
	v := &TBoolInst{}
	v.ptr = p
	return v
}

// TBoolInstMake is MEOS tboolinst_make.
func TBoolInstMake(b bool, t int64) (*Temporal, error) {
	_r0, _err := functions.TboolinstMake(b, t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
