package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBoolSeq struct {
	handle
}

// TBoolSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBoolSeqFromPointer(p unsafe.Pointer) *TBoolSeq {
	if p == nil {
		return nil
	}
	v := &TBoolSeq{}
	v.ptr = p
	return v
}

// TBoolSeqFromBaseTstzset is MEOS tboolseq_from_base_tstzset.
func TBoolSeqFromBaseTstzset(b bool, s *Set) (*Temporal, error) {
	_r0, _err := functions.TboolseqFromBaseTstzset(b, functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TBoolSeqFromBaseTstzspan is MEOS tboolseq_from_base_tstzspan.
func TBoolSeqFromBaseTstzspan(b bool, s *Span) (*Temporal, error) {
	_r0, _err := functions.TboolseqFromBaseTstzspan(b, functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
