package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TBool struct {
	TAlpha
}

// TBoolFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TBoolFromPointer(p unsafe.Pointer) *TBool {
	if p == nil {
		return nil
	}
	v := &TBool{}
	v.ptr = p
	return v
}

// TBoolFromMFJSON is MEOS tbool_from_mfjson.
func TBoolFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TboolFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TBoolIn is MEOS tbool_in.
func TBoolIn(str string) (*Temporal, error) {
	_r0, _err := functions.TboolIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tbool_out.
func (x *TBool) Out() (string, error) {
	_r0, _err := functions.TboolOut(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TBoolFromBaseTemp is MEOS tbool_from_base_temp.
func TBoolFromBaseTemp(b bool, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TboolFromBaseTemp(b, functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTint is MEOS tbool_to_tint.
func (x *TBool) ToTint() (*Temporal, error) {
	_r0, _err := functions.TboolToTint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tbool_end_value.
func (x *TBool) EndValue() (bool, error) {
	_r0, _err := functions.TboolEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// StartValue is MEOS tbool_start_value.
func (x *TBool) StartValue() (bool, error) {
	_r0, _err := functions.TboolStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// ValueAtTimestamptz is MEOS tbool_value_at_timestamptz.
func (x *TBool) ValueAtTimestamptz(t int64, strict bool) (bool, bool, error) {
	_found, _value, _err := functions.TboolValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// ValueN is MEOS tbool_value_n.
func (x *TBool) ValueN(n int) (bool, bool, error) {
	_found, _value, _err := functions.TboolValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Values is MEOS tbool_values.
func (x *TBool) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TboolValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// AtValue is MEOS tbool_at_value.
func (x *TBool) AtValue(b bool) (*Temporal, error) {
	_r0, _err := functions.TboolAtValue(functions.TemporalFromPointer(x.Pointer()), b)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS tbool_minus_value.
func (x *TBool) MinusValue(b bool) (*Temporal, error) {
	_r0, _err := functions.TboolMinusValue(functions.TemporalFromPointer(x.Pointer()), b)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// WhenTrue is MEOS tbool_when_true.
func (x *TBool) WhenTrue() (*SpanSet, error) {
	_r0, _err := functions.TboolWhenTrue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}
