package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TCbufferSeqSet struct {
	handle
}

// TCbufferSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TCbufferSeqSetFromPointer(p unsafe.Pointer) *TCbufferSeqSet {
	if p == nil {
		return nil
	}
	v := &TCbufferSeqSet{}
	v.ptr = p
	return v
}

// TCbufferSeqSetFromBaseTstzspanset is MEOS tcbufferseqset_from_base_tstzspanset.
func TCbufferSeqSetFromBaseTstzspanset(cb *Cbuffer, ss *SpanSet, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TcbufferseqsetFromBaseTstzspanset(functions.CbufferFromPointer(cb.Pointer()), functions.SpanSetFromPointer(ss.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
