package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TCbufferInst struct {
	handle
}

// TCbufferInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TCbufferInstFromPointer(p unsafe.Pointer) *TCbufferInst {
	if p == nil {
		return nil
	}
	v := &TCbufferInst{}
	v.ptr = p
	return v
}

// TCbufferInstMake is MEOS tcbufferinst_make.
func TCbufferInstMake(cb *Cbuffer, t int64) (*Temporal, error) {
	_r0, _err := functions.TcbufferinstMake(functions.CbufferFromPointer(cb.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
