package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TCbuffer struct {
	TSpatial
}

// TCbufferFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TCbufferFromPointer(p unsafe.Pointer) *TCbuffer {
	if p == nil {
		return nil
	}
	v := &TCbuffer{}
	v.ptr = p
	return v
}

// TCbufferIn is MEOS tcbuffer_in.
func TCbufferIn(str string) (*Temporal, error) {
	_r0, _err := functions.TcbufferIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TCbufferFromMFJSON is MEOS tcbuffer_from_mfjson.
func TCbufferFromMFJSON(mfjson string) (*Temporal, error) {
	_r0, _err := functions.TcbufferFromMFJSON(mfjson)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Make is MEOS tcbuffer_make.
func (x *TCbuffer) Make(tfloat *Temporal) (*Temporal, error) {
	_r0, _err := functions.TcbufferMake(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(tfloat.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TCbufferFromBaseTemp is MEOS tcbuffer_from_base_temp.
func TCbufferFromBaseTemp(cb *Cbuffer, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TcbufferFromBaseTemp(functions.CbufferFromPointer(cb.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tcbuffer_end_value.
func (x *TCbuffer) EndValue() (*Cbuffer, error) {
	_r0, _err := functions.TcbufferEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// Points is MEOS tcbuffer_points.
func (x *TCbuffer) Points() (*Set, error) {
	_r0, _err := functions.TcbufferPoints(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Radius is MEOS tcbuffer_radius.
func (x *TCbuffer) Radius() (*Set, error) {
	_r0, _err := functions.TcbufferRadius(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// TraversedArea is MEOS tcbuffer_traversed_area.
func (x *TCbuffer) TraversedArea(unary_union bool) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TcbufferTraversedArea(functions.TemporalFromPointer(x.Pointer()), unary_union)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ConvexHull is MEOS tcbuffer_convex_hull.
func (x *TCbuffer) ConvexHull() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TcbufferConvexHull(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS tcbuffer_start_value.
func (x *TCbuffer) StartValue() (*Cbuffer, error) {
	_r0, _err := functions.TcbufferStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return CbufferFromPointer(_r0.Pointer()), nil
}

// ValueAtTimestamptz is MEOS tcbuffer_value_at_timestamptz.
func (x *TCbuffer) ValueAtTimestamptz(t int64, strict bool) (*Cbuffer, bool, error) {
	_found, _value, _err := functions.TcbufferValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return CbufferFromPointer(_value.Pointer()), true, nil
}

// ValueN is MEOS tcbuffer_value_n.
func (x *TCbuffer) ValueN(n int) (*Cbuffer, bool, error) {
	_found, _value, _err := functions.TcbufferValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return CbufferFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS tcbuffer_values.
func (x *TCbuffer) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TcbufferValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ToTfloat is MEOS tcbuffer_to_tfloat.
func (x *TCbuffer) ToTfloat() (*Temporal, error) {
	_r0, _err := functions.TcbufferToTfloat(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeompoint is MEOS tcbuffer_to_tgeompoint.
func (x *TCbuffer) ToTgeompoint() (*Temporal, error) {
	_r0, _err := functions.TcbufferToTgeompoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Expand is MEOS tcbuffer_expand.
func (x *TCbuffer) Expand(dist float64) (*Temporal, error) {
	_r0, _err := functions.TcbufferExpand(functions.TemporalFromPointer(x.Pointer()), dist)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtCbuffer is MEOS tcbuffer_at_cbuffer.
func (x *TCbuffer) AtCbuffer(cb *Cbuffer) (*Temporal, error) {
	_r0, _err := functions.TcbufferAtCbuffer(functions.TemporalFromPointer(x.Pointer()), functions.CbufferFromPointer(cb.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtGeom is MEOS tcbuffer_at_geom.
func (x *TCbuffer) AtGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TcbufferAtGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtStbox is MEOS tcbuffer_at_stbox.
func (x *TCbuffer) AtStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TcbufferAtSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusCbuffer is MEOS tcbuffer_minus_cbuffer.
func (x *TCbuffer) MinusCbuffer(cb *Cbuffer) (*Temporal, error) {
	_r0, _err := functions.TcbufferMinusCbuffer(functions.TemporalFromPointer(x.Pointer()), functions.CbufferFromPointer(cb.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusGeom is MEOS tcbuffer_minus_geom.
func (x *TCbuffer) MinusGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TcbufferMinusGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusStbox is MEOS tcbuffer_minus_stbox.
func (x *TCbuffer) MinusStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TcbufferMinusSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
