package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TCbufferSeq struct {
	handle
}

// TCbufferSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TCbufferSeqFromPointer(p unsafe.Pointer) *TCbufferSeq {
	if p == nil {
		return nil
	}
	v := &TCbufferSeq{}
	v.ptr = p
	return v
}

// TCbufferSeqFromBaseTstzset is MEOS tcbufferseq_from_base_tstzset.
func TCbufferSeqFromBaseTstzset(cb *Cbuffer, s *Set) (*Temporal, error) {
	_r0, _err := functions.TcbufferseqFromBaseTstzset(functions.CbufferFromPointer(cb.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TCbufferSeqFromBaseTstzspan is MEOS tcbufferseq_from_base_tstzspan.
func TCbufferSeqFromBaseTstzspan(cb *Cbuffer, s *Span, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TcbufferseqFromBaseTstzspan(functions.CbufferFromPointer(cb.Pointer()), functions.SpanFromPointer(s.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
