package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TextSet struct {
	Set
}

// TextSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TextSetFromPointer(p unsafe.Pointer) *TextSet {
	if p == nil {
		return nil
	}
	v := &TextSet{}
	v.ptr = p
	return v
}

// TextSetIn is MEOS textset_in.
func TextSetIn(str string) (*Set, error) {
	_r0, _err := functions.TextsetIn(str)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Out is MEOS textset_out.
func (x *TextSet) Out() (string, error) {
	_r0, _err := functions.TextsetOut(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TextSetMake is MEOS textset_make.
func TextSetMake(values unsafe.Pointer, count int) (*Set, error) {
	_r0, _err := functions.TextsetMake(values, count)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS textset_end_value.
func (x *TextSet) EndValue() (string, error) {
	_r0, _err := functions.TextsetEndValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// StartValue is MEOS textset_start_value.
func (x *TextSet) StartValue() (string, error) {
	_r0, _err := functions.TextsetStartValue(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ValueN is MEOS textset_value_n.
func (x *TextSet) ValueN(n int) (string, bool, error) {
	_found, _value, _err := functions.TextsetValueN(functions.SetFromPointer(x.Pointer()), n)
	if _err != nil {
		return "", false, _err
	}
	if !_found {
		return "", false, nil
	}
	return _value, true, nil
}

// Values is MEOS textset_values.
func (x *TextSet) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TextsetValues(functions.SetFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Initcap is MEOS textset_initcap.
func (x *TextSet) Initcap() (*Set, error) {
	_r0, _err := functions.TextsetInitcap(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS textset_lower.
func (x *TextSet) Lower() (*Set, error) {
	_r0, _err := functions.TextsetLower(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Upper is MEOS textset_upper.
func (x *TextSet) Upper() (*Set, error) {
	_r0, _err := functions.TextsetUpper(functions.SetFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
