package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type Text struct {
	Value
}

// TextFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TextFromPointer(p unsafe.Pointer) *Text {
	if p == nil {
		return nil
	}
	v := &Text{}
	v.ptr = p
	return v
}

// TextIn is MEOS text_in.
func TextIn(str string) (string, error) {
	_r0, _err := functions.TextIn(str)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TextOut is MEOS text_out.
func TextOut(txt string) (string, error) {
	_r0, _err := functions.TextOut(txt)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TextInitcap is MEOS text_initcap.
func TextInitcap(txt string) (string, error) {
	_r0, _err := functions.TextInitcap(txt)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TextLower is MEOS text_lower.
func TextLower(txt string) (string, error) {
	_r0, _err := functions.TextLower(txt)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TextUpper is MEOS text_upper.
func TextUpper(txt string) (string, error) {
	_r0, _err := functions.TextUpper(txt)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TextToSet is MEOS text_to_set.
func TextToSet(txt string) (*Set, error) {
	_r0, _err := functions.TextToSet(txt)
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}
