package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TFloatSeqSet struct {
	handle
}

// TFloatSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TFloatSeqSetFromPointer(p unsafe.Pointer) *TFloatSeqSet {
	if p == nil {
		return nil
	}
	v := &TFloatSeqSet{}
	v.ptr = p
	return v
}

// TFloatSeqSetFromBaseTstzspanset is MEOS tfloatseqset_from_base_tstzspanset.
func TFloatSeqSetFromBaseTstzspanset(d float64, ss *SpanSet, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TfloatseqsetFromBaseTstzspanset(d, functions.SpanSetFromPointer(ss.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
