package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TFloatSeq struct {
	handle
}

// TFloatSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TFloatSeqFromPointer(p unsafe.Pointer) *TFloatSeq {
	if p == nil {
		return nil
	}
	v := &TFloatSeq{}
	v.ptr = p
	return v
}

// TFloatSeqFromBaseTstzset is MEOS tfloatseq_from_base_tstzset.
func TFloatSeqFromBaseTstzset(d float64, s *Set) (*Temporal, error) {
	_r0, _err := functions.TfloatseqFromBaseTstzset(d, functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TFloatSeqFromBaseTstzspan is MEOS tfloatseq_from_base_tstzspan.
func TFloatSeqFromBaseTstzspan(d float64, s *Span, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TfloatseqFromBaseTstzspan(d, functions.SpanFromPointer(s.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
