package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TFloatInst struct {
	handle
}

// TFloatInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TFloatInstFromPointer(p unsafe.Pointer) *TFloatInst {
	if p == nil {
		return nil
	}
	v := &TFloatInst{}
	v.ptr = p
	return v
}

// TFloatInstMake is MEOS tfloatinst_make.
func TFloatInstMake(d float64, t int64) (*Temporal, error) {
	_r0, _err := functions.TfloatinstMake(d, t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
