package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TGeometry struct {
	TGeo
}

// TGeometryFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeometryFromPointer(p unsafe.Pointer) *TGeometry {
	if p == nil {
		return nil
	}
	v := &TGeometry{}
	v.ptr = p
	return v
}

// TGeometryFromMFJSON is MEOS tgeometry_from_mfjson.
func TGeometryFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TgeometryFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TGeometryIn is MEOS tgeometry_in.
func TGeometryIn(str string) (*Temporal, error) {
	_r0, _err := functions.TgeometryIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeography is MEOS tgeometry_to_tgeography.
func (x *TGeometry) ToTgeography() (*Temporal, error) {
	_r0, _err := functions.TgeometryToTgeography(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeompoint is MEOS tgeometry_to_tgeompoint.
func (x *TGeometry) ToTgeompoint() (*Temporal, error) {
	_r0, _err := functions.TgeometryToTgeompoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTcbuffer is MEOS tgeometry_to_tcbuffer.
func (x *TGeometry) ToTcbuffer() (*Temporal, error) {
	_r0, _err := functions.TgeometryToTcbuffer(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
