package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeogPointSeqSet struct {
	handle
}

// TGeogPointSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeogPointSeqSetFromPointer(p unsafe.Pointer) *TGeogPointSeqSet {
	if p == nil {
		return nil
	}
	v := &TGeogPointSeqSet{}
	v.ptr = p
	return v
}
