package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TGeomPoint struct {
	TPoint
}

// TGeomPointFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeomPointFromPointer(p unsafe.Pointer) *TGeomPoint {
	if p == nil {
		return nil
	}
	v := &TGeomPoint{}
	v.ptr = p
	return v
}

// TGeomPointFromMFJSON is MEOS tgeompoint_from_mfjson.
func TGeomPointFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TgeompointFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TGeomPointIn is MEOS tgeompoint_in.
func TGeomPointIn(str string) (*Temporal, error) {
	_r0, _err := functions.TgeompointIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeometry is MEOS tgeompoint_to_tgeometry.
func (x *TGeomPoint) ToTgeometry() (*Temporal, error) {
	_r0, _err := functions.TgeompointToTgeometry(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTh3index is MEOS tgeompoint_to_th3index.
func (x *TGeomPoint) ToTh3index(resolution int32) (*Temporal, error) {
	_r0, _err := functions.TgeompointToTh3index(functions.TemporalFromPointer(x.Pointer()), resolution)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTnpoint is MEOS tgeompoint_to_tnpoint.
func (x *TGeomPoint) ToTnpoint() (*Temporal, error) {
	_r0, _err := functions.TgeompointToTnpoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
