package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeographyInst struct {
	handle
}

// TGeographyInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeographyInstFromPointer(p unsafe.Pointer) *TGeographyInst {
	if p == nil {
		return nil
	}
	v := &TGeographyInst{}
	v.ptr = p
	return v
}
