package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TGeography struct {
	TGeo
}

// TGeographyFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeographyFromPointer(p unsafe.Pointer) *TGeography {
	if p == nil {
		return nil
	}
	v := &TGeography{}
	v.ptr = p
	return v
}

// TGeographyFromMFJSON is MEOS tgeography_from_mfjson.
func TGeographyFromMFJSON(mfjson string) (*Temporal, error) {
	_r0, _err := functions.TgeographyFromMFJSON(mfjson)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TGeographyIn is MEOS tgeography_in.
func TGeographyIn(str string) (*Temporal, error) {
	_r0, _err := functions.TgeographyIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeogpoint is MEOS tgeography_to_tgeogpoint.
func (x *TGeography) ToTgeogpoint() (*Temporal, error) {
	_r0, _err := functions.TgeographyToTgeogpoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeometry is MEOS tgeography_to_tgeometry.
func (x *TGeography) ToTgeometry() (*Temporal, error) {
	_r0, _err := functions.TgeographyToTgeometry(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
