package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeogPointSeq struct {
	handle
}

// TGeogPointSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeogPointSeqFromPointer(p unsafe.Pointer) *TGeogPointSeq {
	if p == nil {
		return nil
	}
	v := &TGeogPointSeq{}
	v.ptr = p
	return v
}
