package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeometrySeqSet struct {
	handle
}

// TGeometrySeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeometrySeqSetFromPointer(p unsafe.Pointer) *TGeometrySeqSet {
	if p == nil {
		return nil
	}
	v := &TGeometrySeqSet{}
	v.ptr = p
	return v
}
