package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TGeogPoint struct {
	TPoint
}

// TGeogPointFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeogPointFromPointer(p unsafe.Pointer) *TGeogPoint {
	if p == nil {
		return nil
	}
	v := &TGeogPoint{}
	v.ptr = p
	return v
}

// TGeogPointFromMFJSON is MEOS tgeogpoint_from_mfjson.
func TGeogPointFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TgeogpointFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TGeogPointIn is MEOS tgeogpoint_in.
func TGeogPointIn(str string) (*Temporal, error) {
	_r0, _err := functions.TgeogpointIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeography is MEOS tgeogpoint_to_tgeography.
func (x *TGeogPoint) ToTgeography() (*Temporal, error) {
	_r0, _err := functions.TgeogpointToTgeography(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTh3index is MEOS tgeogpoint_to_th3index.
func (x *TGeogPoint) ToTh3index(resolution int32) (*Temporal, error) {
	_r0, _err := functions.TgeogpointToTh3index(functions.TemporalFromPointer(x.Pointer()), resolution)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// GreatCircleDistance is MEOS tgeogpoint_great_circle_distance.
func (x *TGeogPoint) GreatCircleDistance(b *Temporal) (*Temporal, error) {
	_r0, _err := functions.TgeogpointGreatCircleDistance(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(b.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
