package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeographySeqSet struct {
	handle
}

// TGeographySeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeographySeqSetFromPointer(p unsafe.Pointer) *TGeographySeqSet {
	if p == nil {
		return nil
	}
	v := &TGeographySeqSet{}
	v.ptr = p
	return v
}
