package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeometryInst struct {
	handle
}

// TGeometryInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeometryInstFromPointer(p unsafe.Pointer) *TGeometryInst {
	if p == nil {
		return nil
	}
	v := &TGeometryInst{}
	v.ptr = p
	return v
}
