package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeographySeq struct {
	handle
}

// TGeographySeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeographySeqFromPointer(p unsafe.Pointer) *TGeographySeq {
	if p == nil {
		return nil
	}
	v := &TGeographySeq{}
	v.ptr = p
	return v
}
