package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeomPointSeq struct {
	handle
}

// TGeomPointSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeomPointSeqFromPointer(p unsafe.Pointer) *TGeomPointSeq {
	if p == nil {
		return nil
	}
	v := &TGeomPointSeq{}
	v.ptr = p
	return v
}
