package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeomPointSeqSet struct {
	handle
}

// TGeomPointSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeomPointSeqSetFromPointer(p unsafe.Pointer) *TGeomPointSeqSet {
	if p == nil {
		return nil
	}
	v := &TGeomPointSeqSet{}
	v.ptr = p
	return v
}
