package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeogPointInst struct {
	handle
}

// TGeogPointInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeogPointInstFromPointer(p unsafe.Pointer) *TGeogPointInst {
	if p == nil {
		return nil
	}
	v := &TGeogPointInst{}
	v.ptr = p
	return v
}
