package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeometrySeq struct {
	handle
}

// TGeometrySeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeometrySeqFromPointer(p unsafe.Pointer) *TGeometrySeq {
	if p == nil {
		return nil
	}
	v := &TGeometrySeq{}
	v.ptr = p
	return v
}
