package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TGeomPointInst struct {
	handle
}

// TGeomPointInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TGeomPointInstFromPointer(p unsafe.Pointer) *TGeomPointInst {
	if p == nil {
		return nil
	}
	v := &TGeomPointInst{}
	v.ptr = p
	return v
}
