package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type TInstant struct {
	Temporal
}

// TInstantFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TInstantFromPointer(p unsafe.Pointer) *TInstant {
	if p == nil {
		return nil
	}
	v := &TInstant{}
	v.ptr = p
	return v
}
