package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TIntInst struct {
	handle
}

// TIntInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TIntInstFromPointer(p unsafe.Pointer) *TIntInst {
	if p == nil {
		return nil
	}
	v := &TIntInst{}
	v.ptr = p
	return v
}

// TIntInstMake is MEOS tintinst_make.
func TIntInstMake(i int, t int64) (*Temporal, error) {
	_r0, _err := functions.TintinstMake(i, t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
