package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TIntSeqSet struct {
	handle
}

// TIntSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TIntSeqSetFromPointer(p unsafe.Pointer) *TIntSeqSet {
	if p == nil {
		return nil
	}
	v := &TIntSeqSet{}
	v.ptr = p
	return v
}

// TIntSeqSetFromBaseTstzspanset is MEOS tintseqset_from_base_tstzspanset.
func TIntSeqSetFromBaseTstzspanset(i int, ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TintseqsetFromBaseTstzspanset(i, functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
