package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TIntSeq struct {
	handle
}

// TIntSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TIntSeqFromPointer(p unsafe.Pointer) *TIntSeq {
	if p == nil {
		return nil
	}
	v := &TIntSeq{}
	v.ptr = p
	return v
}

// TIntSeqFromBaseTstzset is MEOS tintseq_from_base_tstzset.
func TIntSeqFromBaseTstzset(i int, s *Set) (*Temporal, error) {
	_r0, _err := functions.TintseqFromBaseTstzset(i, functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TIntSeqFromBaseTstzspan is MEOS tintseq_from_base_tstzspan.
func TIntSeqFromBaseTstzspan(i int, s *Span) (*Temporal, error) {
	_r0, _err := functions.TintseqFromBaseTstzspan(i, functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
