package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TJsonbSeq struct {
	handle
}

// TJsonbSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TJsonbSeqFromPointer(p unsafe.Pointer) *TJsonbSeq {
	if p == nil {
		return nil
	}
	v := &TJsonbSeq{}
	v.ptr = p
	return v
}

// TJsonbSeqFromBaseTstzset is MEOS tjsonbseq_from_base_tstzset.
func TJsonbSeqFromBaseTstzset(jsonb *Jsonb, s *Set) (*Temporal, error) {
	_r0, _err := functions.TjsonbseqFromBaseTstzset(functions.JsonbFromPointer(jsonb.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TJsonbSeqFromBaseTstzspan is MEOS tjsonbseq_from_base_tstzspan.
func TJsonbSeqFromBaseTstzspan(jsonb *Jsonb, sp *Span) (*Temporal, error) {
	_r0, _err := functions.TjsonbseqFromBaseTstzspan(functions.JsonbFromPointer(jsonb.Pointer()), functions.SpanFromPointer(sp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
