package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TJsonbInst struct {
	handle
}

// TJsonbInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TJsonbInstFromPointer(p unsafe.Pointer) *TJsonbInst {
	if p == nil {
		return nil
	}
	v := &TJsonbInst{}
	v.ptr = p
	return v
}

// TJsonbInstMake is MEOS tjsonbinst_make.
func TJsonbInstMake(jsonb *Jsonb, t int64) (*Temporal, error) {
	_r0, _err := functions.TjsonbinstMake(functions.JsonbFromPointer(jsonb.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
