package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TJsonbSeqSet struct {
	handle
}

// TJsonbSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TJsonbSeqSetFromPointer(p unsafe.Pointer) *TJsonbSeqSet {
	if p == nil {
		return nil
	}
	v := &TJsonbSeqSet{}
	v.ptr = p
	return v
}

// TJsonbSeqSetFromBaseTstzspanset is MEOS tjsonbseqset_from_base_tstzspanset.
func TJsonbSeqSetFromBaseTstzspanset(jsonb *Jsonb, ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TjsonbseqsetFromBaseTstzspanset(functions.JsonbFromPointer(jsonb.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
