package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TJsonb struct {
	TAlpha
}

// TJsonbFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TJsonbFromPointer(p unsafe.Pointer) *TJsonb {
	if p == nil {
		return nil
	}
	v := &TJsonb{}
	v.ptr = p
	return v
}

// TJsonbFromMFJSON is MEOS tjsonb_from_mfjson.
func TJsonbFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TjsonbFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TJsonbIn is MEOS tjsonb_in.
func TJsonbIn(str string) (*Temporal, error) {
	_r0, _err := functions.TjsonbIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tjsonb_out.
func (x *TJsonb) Out() (string, error) {
	_r0, _err := functions.TjsonbOut(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TJsonbFromBaseTemp is MEOS tjsonb_from_base_temp.
func TJsonbFromBaseTemp(jsonb *Jsonb, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TjsonbFromBaseTemp(functions.JsonbFromPointer(jsonb.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTtext is MEOS tjsonb_to_ttext.
func (x *TJsonb) ToTtext() (*Temporal, error) {
	_r0, _err := functions.TjsonbToTtext(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tjsonb_end_value.
func (x *TJsonb) EndValue() (*Jsonb, error) {
	_r0, _err := functions.TjsonbEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS tjsonb_start_value.
func (x *TJsonb) StartValue() (*Jsonb, error) {
	_r0, _err := functions.TjsonbStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return JsonbFromPointer(_r0.Pointer()), nil
}

// ValueAtTimestamptz is MEOS tjsonb_value_at_timestamptz.
func (x *TJsonb) ValueAtTimestamptz(t int64, strict bool) (*Jsonb, bool, error) {
	_found, _value, _err := functions.TjsonbValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return JsonbFromPointer(_value.Pointer()), true, nil
}

// ValueN is MEOS tjsonb_value_n.
func (x *TJsonb) ValueN(n int) (*Jsonb, bool, error) {
	_found, _value, _err := functions.TjsonbValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return JsonbFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS tjsonb_values.
func (x *TJsonb) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TjsonbValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// ArrayElement is MEOS tjsonb_array_element.
func (x *TJsonb) ArrayElement(idx int, astext bool, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbArrayElement(functions.TemporalFromPointer(x.Pointer()), idx, astext, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ArrayLength is MEOS tjsonb_array_length.
func (x *TJsonb) ArrayLength() (*Temporal, error) {
	_r0, _err := functions.TjsonbArrayLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Delete is MEOS tjsonb_delete.
func (x *TJsonb) Delete(key string) (*Temporal, error) {
	_r0, _err := functions.TjsonbDelete(functions.TemporalFromPointer(x.Pointer()), key)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteArray is MEOS tjsonb_delete_array.
func (x *TJsonb) DeleteArray(keys unsafe.Pointer, count int) (*Temporal, error) {
	_r0, _err := functions.TjsonbDeleteArray(functions.TemporalFromPointer(x.Pointer()), keys, count)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeleteIndex is MEOS tjsonb_delete_index.
func (x *TJsonb) DeleteIndex(idx int) (*Temporal, error) {
	_r0, _err := functions.TjsonbDeleteIndex(functions.TemporalFromPointer(x.Pointer()), idx)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeletePath is MEOS tjsonb_delete_path.
func (x *TJsonb) DeletePath(path_elems unsafe.Pointer, path_len int) (*Temporal, error) {
	_r0, _err := functions.TjsonbDeletePath(functions.TemporalFromPointer(x.Pointer()), path_elems, path_len)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Exists is MEOS tjsonb_exists.
func (x *TJsonb) Exists(key string) (*Temporal, error) {
	_r0, _err := functions.TjsonbExists(functions.TemporalFromPointer(x.Pointer()), key)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ExistsAll is MEOS tjsonb_exists_all.
func (x *TJsonb) ExistsAll(keys unsafe.Pointer, count int) (*Temporal, error) {
	_r0, _err := functions.TjsonbExistsAll(functions.TemporalFromPointer(x.Pointer()), keys, count)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ExistsAny is MEOS tjsonb_exists_any.
func (x *TJsonb) ExistsAny(keys unsafe.Pointer, count int) (*Temporal, error) {
	_r0, _err := functions.TjsonbExistsAny(functions.TemporalFromPointer(x.Pointer()), keys, count)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ExistsArray is MEOS tjsonb_exists_array.
func (x *TJsonb) ExistsArray(keys unsafe.Pointer, count int, any bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbExistsArray(functions.TemporalFromPointer(x.Pointer()), keys, count, any)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ExtractPath is MEOS tjsonb_extract_path.
func (x *TJsonb) ExtractPath(path_elems unsafe.Pointer, path_len int, astext bool, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbExtractPath(functions.TemporalFromPointer(x.Pointer()), path_elems, path_len, astext, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Insert is MEOS tjsonb_insert.
func (x *TJsonb) Insert(keys unsafe.Pointer, count int, newjb *Jsonb, after bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbInsert(functions.TemporalFromPointer(x.Pointer()), keys, count, functions.JsonbFromPointer(newjb.Pointer()), after)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ObjectField is MEOS tjsonb_object_field.
func (x *TJsonb) ObjectField(key string, astext bool, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbObjectField(functions.TemporalFromPointer(x.Pointer()), key, astext, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// PathExists is MEOS tjsonb_path_exists.
func (x *TJsonb) PathExists(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbPathExists(functions.TemporalFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// PathMatch is MEOS tjsonb_path_match.
func (x *TJsonb) PathMatch(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbPathMatch(functions.TemporalFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// PathQueryArray is MEOS tjsonb_path_query_array.
func (x *TJsonb) PathQueryArray(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbPathQueryArray(functions.TemporalFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// PathQueryFirst is MEOS tjsonb_path_query_first.
func (x *TJsonb) PathQueryFirst(jp *JsonPath, vars *Jsonb, silent bool, tz bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbPathQueryFirst(functions.TemporalFromPointer(x.Pointer()), functions.JsonPathFromPointer(jp.Pointer()), functions.JsonbFromPointer(vars.Pointer()), silent, tz)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Pretty is MEOS tjsonb_pretty.
func (x *TJsonb) Pretty() (*Temporal, error) {
	_r0, _err := functions.TjsonbPretty(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Set is MEOS tjsonb_set.
func (x *TJsonb) Set(keys unsafe.Pointer, count int, newjb *Jsonb, create bool, handle_null string, lax bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbSet(functions.TemporalFromPointer(x.Pointer()), keys, count, functions.JsonbFromPointer(newjb.Pointer()), create, handle_null, lax)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StripNulls is MEOS tjsonb_strip_nulls.
func (x *TJsonb) StripNulls(strip_in_arrays bool) (*Temporal, error) {
	_r0, _err := functions.TjsonbStripNulls(functions.TemporalFromPointer(x.Pointer()), strip_in_arrays)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTbool is MEOS tjsonb_to_tbool.
func (x *TJsonb) ToTbool(key string, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbToTbool(functions.TemporalFromPointer(x.Pointer()), key, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTfloat is MEOS tjsonb_to_tfloat.
func (x *TJsonb) ToTfloat(key string, interp functions.Interpolation, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbToTfloat(functions.TemporalFromPointer(x.Pointer()), key, interp, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTint is MEOS tjsonb_to_tint.
func (x *TJsonb) ToTint(key string, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbToTint(functions.TemporalFromPointer(x.Pointer()), key, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTtextKey is MEOS tjsonb_to_ttext_key.
func (x *TJsonb) ToTtextKey(key string, null_handle functions.NullHandleType) (*Temporal, error) {
	_r0, _err := functions.TjsonbToTtextKey(functions.TemporalFromPointer(x.Pointer()), key, null_handle)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValue is MEOS tjsonb_at_value.
func (x *TJsonb) AtValue(jsb *Jsonb) (*Temporal, error) {
	_r0, _err := functions.TjsonbAtValue(functions.TemporalFromPointer(x.Pointer()), functions.JsonbFromPointer(jsb.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS tjsonb_minus_value.
func (x *TJsonb) MinusValue(jsb *Jsonb) (*Temporal, error) {
	_r0, _err := functions.TjsonbMinusValue(functions.TemporalFromPointer(x.Pointer()), functions.JsonbFromPointer(jsb.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
