package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TNpointSeq struct {
	handle
}

// TNpointSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TNpointSeqFromPointer(p unsafe.Pointer) *TNpointSeq {
	if p == nil {
		return nil
	}
	v := &TNpointSeq{}
	v.ptr = p
	return v
}

// TNpointSeqFromBaseTstzset is MEOS tnpointseq_from_base_tstzset.
func TNpointSeqFromBaseTstzset(np *Npoint, s *Set) (*Temporal, error) {
	_r0, _err := functions.TnpointseqFromBaseTstzset(functions.NpointFromPointer(np.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TNpointSeqFromBaseTstzspan is MEOS tnpointseq_from_base_tstzspan.
func TNpointSeqFromBaseTstzspan(np *Npoint, s *Span, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TnpointseqFromBaseTstzspan(functions.NpointFromPointer(np.Pointer()), functions.SpanFromPointer(s.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
