package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TNpointInst struct {
	handle
}

// TNpointInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TNpointInstFromPointer(p unsafe.Pointer) *TNpointInst {
	if p == nil {
		return nil
	}
	v := &TNpointInst{}
	v.ptr = p
	return v
}

// TNpointInstMake is MEOS tnpointinst_make.
func TNpointInstMake(np *Npoint, t int64) (*Temporal, error) {
	_r0, _err := functions.TnpointinstMake(functions.NpointFromPointer(np.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
