package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TNpointSeqSet struct {
	handle
}

// TNpointSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TNpointSeqSetFromPointer(p unsafe.Pointer) *TNpointSeqSet {
	if p == nil {
		return nil
	}
	v := &TNpointSeqSet{}
	v.ptr = p
	return v
}

// TNpointSeqSetFromBaseTstzspanset is MEOS tnpointseqset_from_base_tstzspanset.
func TNpointSeqSetFromBaseTstzspanset(np *Npoint, ss *SpanSet, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TnpointseqsetFromBaseTstzspanset(functions.NpointFromPointer(np.Pointer()), functions.SpanSetFromPointer(ss.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
