package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TNpoint struct {
	TSpatial
}

// TNpointFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TNpointFromPointer(p unsafe.Pointer) *TNpoint {
	if p == nil {
		return nil
	}
	v := &TNpoint{}
	v.ptr = p
	return v
}

// TNpointIn is MEOS tnpoint_in.
func TNpointIn(str string) (*Temporal, error) {
	_r0, _err := functions.TnpointIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TNpointFromMFJSON is MEOS tnpoint_from_mfjson.
func TNpointFromMFJSON(mfjson string) (*Temporal, error) {
	_r0, _err := functions.TnpointFromMFJSON(mfjson)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tnpoint_out.
func (x *TNpoint) Out(maxdd int) (string, error) {
	_r0, _err := functions.TnpointOut(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TNpointFromBaseTemp is MEOS tnpoint_from_base_temp.
func TNpointFromBaseTemp(np *Npoint, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TnpointFromBaseTemp(functions.NpointFromPointer(np.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTgeompoint is MEOS tnpoint_to_tgeompoint.
func (x *TNpoint) ToTgeompoint() (*Temporal, error) {
	_r0, _err := functions.TnpointToTgeompoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// CumulativeLength is MEOS tnpoint_cumulative_length.
func (x *TNpoint) CumulativeLength() (*Temporal, error) {
	_r0, _err := functions.TnpointCumulativeLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tnpoint_end_value.
func (x *TNpoint) EndValue() (*Npoint, error) {
	_r0, _err := functions.TnpointEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// Length is MEOS tnpoint_length.
func (x *TNpoint) Length() (float64, error) {
	_r0, _err := functions.TnpointLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Positions is MEOS tnpoint_positions.
func (x *TNpoint) Positions(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TnpointPositions(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Route is MEOS tnpoint_route.
func (x *TNpoint) Route() (int64, error) {
	_r0, _err := functions.TnpointRoute(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Routes is MEOS tnpoint_routes.
func (x *TNpoint) Routes() (*Set, error) {
	_r0, _err := functions.TnpointRoutes(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Speed is MEOS tnpoint_speed.
func (x *TNpoint) Speed() (*Temporal, error) {
	_r0, _err := functions.TnpointSpeed(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS tnpoint_start_value.
func (x *TNpoint) StartValue() (*Npoint, error) {
	_r0, _err := functions.TnpointStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return NpointFromPointer(_r0.Pointer()), nil
}

// Trajectory is MEOS tnpoint_trajectory.
func (x *TNpoint) Trajectory() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TnpointTrajectory(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ValueAtTimestamptz is MEOS tnpoint_value_at_timestamptz.
func (x *TNpoint) ValueAtTimestamptz(t int64, strict bool) (*Npoint, bool, error) {
	_found, _value, _err := functions.TnpointValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return NpointFromPointer(_value.Pointer()), true, nil
}

// ValueN is MEOS tnpoint_value_n.
func (x *TNpoint) ValueN(n int) (*Npoint, bool, error) {
	_found, _value, _err := functions.TnpointValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return NpointFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS tnpoint_values.
func (x *TNpoint) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TnpointValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// Twcentroid is MEOS tnpoint_twcentroid.
func (x *TNpoint) Twcentroid() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TnpointTwcentroid(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// AtGeom is MEOS tnpoint_at_geom.
func (x *TNpoint) AtGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TnpointAtGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtNpoint is MEOS tnpoint_at_npoint.
func (x *TNpoint) AtNpoint(np *Npoint) (*Temporal, error) {
	_r0, _err := functions.TnpointAtNpoint(functions.TemporalFromPointer(x.Pointer()), functions.NpointFromPointer(np.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtNpointset is MEOS tnpoint_at_npointset.
func (x *TNpoint) AtNpointset(s *Set) (*Temporal, error) {
	_r0, _err := functions.TnpointAtNpointset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtStbox is MEOS tnpoint_at_stbox.
func (x *TNpoint) AtStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TnpointAtSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusGeom is MEOS tnpoint_minus_geom.
func (x *TNpoint) MinusGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TnpointMinusGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusNpoint is MEOS tnpoint_minus_npoint.
func (x *TNpoint) MinusNpoint(np *Npoint) (*Temporal, error) {
	_r0, _err := functions.TnpointMinusNpoint(functions.TemporalFromPointer(x.Pointer()), functions.NpointFromPointer(np.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusNpointset is MEOS tnpoint_minus_npointset.
func (x *TNpoint) MinusNpointset(s *Set) (*Temporal, error) {
	_r0, _err := functions.TnpointMinusNpointset(functions.TemporalFromPointer(x.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusStbox is MEOS tnpoint_minus_stbox.
func (x *TNpoint) MinusStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TnpointMinusSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
