package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

// TNumber is temporal numbers; supports linear interpolation.

type TNumber struct {
	Temporal
}

// TNumberFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TNumberFromPointer(p unsafe.Pointer) *TNumber {
	if p == nil {
		return nil
	}
	v := &TNumber{}
	v.ptr = p
	return v
}

// ToSpan is MEOS tnumber_to_span.
func (x *TNumber) ToSpan() (*Span, error) {
	_r0, _err := functions.TnumberToSpan(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanFromPointer(_r0.Pointer()), nil
}

// ToTbox is MEOS tnumber_to_tbox.
func (x *TNumber) ToTbox() (*TBox, error) {
	_r0, _err := functions.TnumberToTBOX(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// Integral is MEOS tnumber_integral.
func (x *TNumber) Integral() (float64, error) {
	_r0, _err := functions.TnumberIntegral(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Twavg is MEOS tnumber_twavg.
func (x *TNumber) Twavg() (float64, error) {
	_r0, _err := functions.TnumberTwavg(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Valuespans is MEOS tnumber_valuespans.
func (x *TNumber) Valuespans() (*SpanSet, error) {
	_r0, _err := functions.TnumberValuespans(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SpanSetFromPointer(_r0.Pointer()), nil
}

// AtSpan is MEOS tnumber_at_span.
func (x *TNumber) AtSpan(span *Span) (*Temporal, error) {
	_r0, _err := functions.TnumberAtSpan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(span.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtSpanset is MEOS tnumber_at_spanset.
func (x *TNumber) AtSpanset(ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TnumberAtSpanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtTbox is MEOS tnumber_at_tbox.
func (x *TNumber) AtTbox(box *TBox) (*Temporal, error) {
	_r0, _err := functions.TnumberAtTBOX(functions.TemporalFromPointer(x.Pointer()), functions.TBoxFromPointer(box.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusSpan is MEOS tnumber_minus_span.
func (x *TNumber) MinusSpan(span *Span) (*Temporal, error) {
	_r0, _err := functions.TnumberMinusSpan(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(span.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusSpanset is MEOS tnumber_minus_spanset.
func (x *TNumber) MinusSpanset(ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TnumberMinusSpanset(functions.TemporalFromPointer(x.Pointer()), functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusTbox is MEOS tnumber_minus_tbox.
func (x *TNumber) MinusTbox(box *TBox) (*Temporal, error) {
	_r0, _err := functions.TnumberMinusTBOX(functions.TemporalFromPointer(x.Pointer()), functions.TBoxFromPointer(box.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// SplitEachNTboxes is MEOS tnumber_split_each_n_tboxes.
func (x *TNumber) SplitEachNTboxes(elem_count int, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TnumberSplitEachNTboxes(functions.TemporalFromPointer(x.Pointer()), elem_count, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// SplitNTboxes is MEOS tnumber_split_n_tboxes.
func (x *TNumber) SplitNTboxes(box_count int, count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TnumberSplitNTboxes(functions.TemporalFromPointer(x.Pointer()), box_count, count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// Tboxes is MEOS tnumber_tboxes.
func (x *TNumber) Tboxes(count unsafe.Pointer) (*TBox, error) {
	_r0, _err := functions.TnumberTboxes(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return TBoxFromPointer(_r0.Pointer()), nil
}

// Abs is MEOS tnumber_abs.
func (x *TNumber) Abs() (*Temporal, error) {
	_r0, _err := functions.TnumberAbs(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Trend is MEOS tnumber_trend.
func (x *TNumber) Trend() (*Temporal, error) {
	_r0, _err := functions.TnumberTrend(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AngularDifference is MEOS tnumber_angular_difference.
func (x *TNumber) AngularDifference() (*Temporal, error) {
	_r0, _err := functions.TnumberAngularDifference(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// DeltaValue is MEOS tnumber_delta_value.
func (x *TNumber) DeltaValue() (*Temporal, error) {
	_r0, _err := functions.TnumberDeltaValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
