package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TPCBox struct {
	Box
}

// TPCBoxFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TPCBoxFromPointer(p unsafe.Pointer) *TPCBox {
	if p == nil {
		return nil
	}
	v := &TPCBox{}
	v.ptr = p
	return v
}

// TPCBoxIn is MEOS tpcbox_in.
func TPCBoxIn(str string) (*TPCBox, error) {
	_r0, _err := functions.TpcboxIn(str)
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}

// Out is MEOS tpcbox_out.
func (x *TPCBox) Out(maxdd int) (string, error) {
	_r0, _err := functions.TpcboxOut(functions.TPCBoxFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TPCBoxMake is MEOS tpcbox_make.
func TPCBoxMake(hasx bool, hasz bool, hast bool, geodetic bool, srid int32, pcid uint32, xmin float64, xmax float64, ymin float64, ymax float64, zmin float64, zmax float64, period *Span) (*TPCBox, error) {
	_r0, _err := functions.TpcboxMake(hasx, hasz, hast, geodetic, srid, pcid, xmin, xmax, ymin, ymax, zmin, zmax, functions.SpanFromPointer(period.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}

// Copy is MEOS tpcbox_copy.
func (x *TPCBox) Copy() (*TPCBox, error) {
	_r0, _err := functions.TpcboxCopy(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}

// Hasx is MEOS tpcbox_hasx.
func (x *TPCBox) Hasx() (bool, error) {
	_r0, _err := functions.TpcboxHasx(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Hasz is MEOS tpcbox_hasz.
func (x *TPCBox) Hasz() (bool, error) {
	_r0, _err := functions.TpcboxHasz(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Hast is MEOS tpcbox_hast.
func (x *TPCBox) Hast() (bool, error) {
	_r0, _err := functions.TpcboxHast(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Geodetic is MEOS tpcbox_geodetic.
func (x *TPCBox) Geodetic() (bool, error) {
	_r0, _err := functions.TpcboxGeodetic(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Xmin is MEOS tpcbox_xmin.
func (x *TPCBox) Xmin() (float64, bool, error) {
	_found, _value, _err := functions.TpcboxXmin(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Xmax is MEOS tpcbox_xmax.
func (x *TPCBox) Xmax() (float64, bool, error) {
	_found, _value, _err := functions.TpcboxXmax(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Ymin is MEOS tpcbox_ymin.
func (x *TPCBox) Ymin() (float64, bool, error) {
	_found, _value, _err := functions.TpcboxYmin(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Ymax is MEOS tpcbox_ymax.
func (x *TPCBox) Ymax() (float64, bool, error) {
	_found, _value, _err := functions.TpcboxYmax(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Zmin is MEOS tpcbox_zmin.
func (x *TPCBox) Zmin() (float64, bool, error) {
	_found, _value, _err := functions.TpcboxZmin(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Zmax is MEOS tpcbox_zmax.
func (x *TPCBox) Zmax() (float64, bool, error) {
	_found, _value, _err := functions.TpcboxZmax(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// Tmin is MEOS tpcbox_tmin.
func (x *TPCBox) Tmin() (int64, bool, error) {
	_found, _value, _err := functions.TpcboxTmin(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// TminInc is MEOS tpcbox_tmin_inc.
func (x *TPCBox) TminInc() (bool, bool, error) {
	_found, _value, _err := functions.TpcboxTminInc(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// Tmax is MEOS tpcbox_tmax.
func (x *TPCBox) Tmax() (int64, bool, error) {
	_found, _value, _err := functions.TpcboxTmax(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// TmaxInc is MEOS tpcbox_tmax_inc.
func (x *TPCBox) TmaxInc() (bool, bool, error) {
	_found, _value, _err := functions.TpcboxTmaxInc(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return false, false, _err
	}
	if !_found {
		return false, false, nil
	}
	return _value, true, nil
}

// SRID is MEOS tpcbox_srid.
func (x *TPCBox) SRID() (int32, error) {
	_r0, _err := functions.TpcboxSRID(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Pcid is MEOS tpcbox_pcid.
func (x *TPCBox) Pcid() (uint32, error) {
	_r0, _err := functions.TpcboxPcid(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// ToStbox is MEOS tpcbox_to_stbox.
func (x *TPCBox) ToStbox() (*STBox, error) {
	_r0, _err := functions.TpcboxToSTBOX(functions.TPCBoxFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// Round is MEOS tpcbox_round.
func (x *TPCBox) Round(maxdd int) (*TPCBox, error) {
	_r0, _err := functions.TpcboxRound(functions.TPCBoxFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}

// SetSRID is MEOS tpcbox_set_srid.
func (x *TPCBox) SetSRID(srid int32) (*TPCBox, error) {
	_r0, _err := functions.TpcboxSetSRID(functions.TPCBoxFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return TPCBoxFromPointer(_r0.Pointer()), nil
}

// Cmp is MEOS tpcbox_cmp.
func (x *TPCBox) Cmp(box2 *TPCBox) (int, error) {
	_r0, _err := functions.TpcboxCmp(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Eq is MEOS tpcbox_eq.
func (x *TPCBox) Eq(box2 *TPCBox) (bool, error) {
	_r0, _err := functions.TpcboxEq(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ne is MEOS tpcbox_ne.
func (x *TPCBox) Ne(box2 *TPCBox) (bool, error) {
	_r0, _err := functions.TpcboxNe(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Lt is MEOS tpcbox_lt.
func (x *TPCBox) Lt(box2 *TPCBox) (bool, error) {
	_r0, _err := functions.TpcboxLt(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Le is MEOS tpcbox_le.
func (x *TPCBox) Le(box2 *TPCBox) (bool, error) {
	_r0, _err := functions.TpcboxLe(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Gt is MEOS tpcbox_gt.
func (x *TPCBox) Gt(box2 *TPCBox) (bool, error) {
	_r0, _err := functions.TpcboxGt(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Ge is MEOS tpcbox_ge.
func (x *TPCBox) Ge(box2 *TPCBox) (bool, error) {
	_r0, _err := functions.TpcboxGe(functions.TPCBoxFromPointer(x.Pointer()), functions.TPCBoxFromPointer(box2.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}
