package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

// TPoint is temporal points. API-level intermediate (C predicate tpoint_type + the tpoint_* method family); NOT drawn in the manual Figure 7.1 (a conceptual diagram) but required so the tpoint_* methods bind to a class — see correction OM-M6.

type TPoint struct {
	TGeo
}

// TPointFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TPointFromPointer(p unsafe.Pointer) *TPoint {
	if p == nil {
		return nil
	}
	v := &TPoint{}
	v.ptr = p
	return v
}

// TPointFromBaseTemp is MEOS tpoint_from_base_temp.
func TPointFromBaseTemp(gs *TRGeometrySeqSet, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TpointFromBaseTemp(functions.GeomFromPointer(gs.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TfloatToGeomeas is MEOS tpoint_tfloat_to_geomeas.
func (x *TPoint) TfloatToGeomeas(measure *Temporal, segmentize bool) (*TRGeometrySeqSet, bool, error) {
	_found, _value, _err := functions.TpointTfloatToGeomeas(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(measure.Pointer()), segmentize)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return TRGeometrySeqSetFromPointer(_value.Pointer()), true, nil
}

// AngularDifference is MEOS tpoint_angular_difference.
func (x *TPoint) AngularDifference() (*Temporal, error) {
	_r0, _err := functions.TpointAngularDifference(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Azimuth is MEOS tpoint_azimuth.
func (x *TPoint) Azimuth() (*Temporal, error) {
	_r0, _err := functions.TpointAzimuth(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// CumulativeLength is MEOS tpoint_cumulative_length.
func (x *TPoint) CumulativeLength() (*Temporal, error) {
	_r0, _err := functions.TpointCumulativeLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Direction is MEOS tpoint_direction.
func (x *TPoint) Direction() (float64, bool, error) {
	_found, _value, _err := functions.TpointDirection(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, false, _err
	}
	if !_found {
		return 0, false, nil
	}
	return _value, true, nil
}

// GetX is MEOS tpoint_get_x.
func (x *TPoint) GetX() (*Temporal, error) {
	_r0, _err := functions.TpointGetX(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// GetY is MEOS tpoint_get_y.
func (x *TPoint) GetY() (*Temporal, error) {
	_r0, _err := functions.TpointGetY(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// GetZ is MEOS tpoint_get_z.
func (x *TPoint) GetZ() (*Temporal, error) {
	_r0, _err := functions.TpointGetZ(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// IsSimple is MEOS tpoint_is_simple.
func (x *TPoint) IsSimple() (bool, error) {
	_r0, _err := functions.TpointIsSimple(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return false, _err
	}
	return _r0, nil
}

// Length is MEOS tpoint_length.
func (x *TPoint) Length() (float64, error) {
	_r0, _err := functions.TpointLength(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// Speed is MEOS tpoint_speed.
func (x *TPoint) Speed() (*Temporal, error) {
	_r0, _err := functions.TpointSpeed(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Trajectory is MEOS tpoint_trajectory.
func (x *TPoint) Trajectory(unary_union bool) (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TpointTrajectory(functions.TemporalFromPointer(x.Pointer()), unary_union)
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// Twcentroid is MEOS tpoint_twcentroid.
func (x *TPoint) Twcentroid() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TpointTwcentroid(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// MakeSimple is MEOS tpoint_make_simple.
func (x *TPoint) MakeSimple(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TpointMakeSimple(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// AtElevation is MEOS tpoint_at_elevation.
func (x *TPoint) AtElevation(s *Span) (*Temporal, error) {
	_r0, _err := functions.TpointAtElevation(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtGeom is MEOS tpoint_at_geom.
func (x *TPoint) AtGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TpointAtGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtValue is MEOS tpoint_at_value.
func (x *TPoint) AtValue(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TpointAtValue(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusElevation is MEOS tpoint_minus_elevation.
func (x *TPoint) MinusElevation(s *Span) (*Temporal, error) {
	_r0, _err := functions.TpointMinusElevation(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusGeom is MEOS tpoint_minus_geom.
func (x *TPoint) MinusGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TpointMinusGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS tpoint_minus_value.
func (x *TPoint) MinusValue(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TpointMinusValue(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
