package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TPose struct {
	TSpatial
}

// TPoseFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TPoseFromPointer(p unsafe.Pointer) *TPose {
	if p == nil {
		return nil
	}
	v := &TPose{}
	v.ptr = p
	return v
}

// TPoseFromGeopose is MEOS tpose_from_geopose.
func TPoseFromGeopose(json string) (*Temporal, error) {
	_r0, _err := functions.TposeFromGeopose(json)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AsGeopose is MEOS tpose_as_geopose.
func (x *TPose) AsGeopose(conformance int, precision int) (string, error) {
	_r0, _err := functions.TposeAsGeopose(functions.TemporalFromPointer(x.Pointer()), conformance, precision)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsGeoposeStreamElement is MEOS tpose_as_geopose_stream_element.
func (x *TPose) AsGeoposeStreamElement(inst *Temporal, precision int) (string, error) {
	_r0, _err := functions.TposeAsGeoposeStreamElement(functions.TemporalFromPointer(x.Pointer()), functions.TInstantFromPointer(inst.Pointer()), precision)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsGeoposeStream is MEOS tpose_as_geopose_stream.
func (x *TPose) AsGeoposeStream(precision int) (string, error) {
	_r0, _err := functions.TposeAsGeoposeStream(functions.TemporalFromPointer(x.Pointer()), precision)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ApplyGeo is MEOS tpose_apply_geo.
func (x *TPose) ApplyGeo(body *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TposeApplyGeo(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(body.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ComposePose is MEOS tpose_compose_pose.
func (x *TPose) ComposePose(frame *Pose) (*Temporal, error) {
	_r0, _err := functions.TposeComposePose(functions.TemporalFromPointer(x.Pointer()), functions.PoseFromPointer(frame.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ComposeTpose is MEOS tpose_compose_tpose.
func (x *TPose) ComposeTpose(frame *Temporal) (*Temporal, error) {
	_r0, _err := functions.TposeComposeTpose(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(frame.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Inverse is MEOS tpose_inverse.
func (x *TPose) Inverse() (*Temporal, error) {
	_r0, _err := functions.TposeInverse(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TPoseFromMFJSON is MEOS tpose_from_mfjson.
func TPoseFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TposeFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TPoseIn is MEOS tpose_in.
func TPoseIn(str string) (*Temporal, error) {
	_r0, _err := functions.TposeIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TPoseFromBaseTemp is MEOS tpose_from_base_temp.
func TPoseFromBaseTemp(pose *Pose, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TposeFromBaseTemp(functions.PoseFromPointer(pose.Pointer()), functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Make is MEOS tpose_make.
func (x *TPose) Make(ttheta *Temporal) (*Temporal, error) {
	_r0, _err := functions.TposeMake(functions.TemporalFromPointer(x.Pointer()), functions.TemporalFromPointer(ttheta.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTpoint is MEOS tpose_to_tpoint.
func (x *TPose) ToTpoint() (*Temporal, error) {
	_r0, _err := functions.TposeToTpoint(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS tpose_end_value.
func (x *TPose) EndValue() (*Pose, error) {
	_r0, _err := functions.TposeEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// Points is MEOS tpose_points.
func (x *TPose) Points() (*Set, error) {
	_r0, _err := functions.TposePoints(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return SetFromPointer(_r0.Pointer()), nil
}

// Yaw is MEOS tpose_yaw.
func (x *TPose) Yaw() (*Temporal, error) {
	_r0, _err := functions.TposeYaw(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Pitch is MEOS tpose_pitch.
func (x *TPose) Pitch() (*Temporal, error) {
	_r0, _err := functions.TposePitch(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Roll is MEOS tpose_roll.
func (x *TPose) Roll() (*Temporal, error) {
	_r0, _err := functions.TposeRoll(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Speed is MEOS tpose_speed.
func (x *TPose) Speed() (*Temporal, error) {
	_r0, _err := functions.TposeSpeed(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AngularSpeed is MEOS tpose_angular_speed.
func (x *TPose) AngularSpeed() (*Temporal, error) {
	_r0, _err := functions.TposeAngularSpeed(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// StartValue is MEOS tpose_start_value.
func (x *TPose) StartValue() (*Pose, error) {
	_r0, _err := functions.TposeStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return PoseFromPointer(_r0.Pointer()), nil
}

// Trajectory is MEOS tpose_trajectory.
func (x *TPose) Trajectory() (*TRGeometrySeqSet, error) {
	_r0, _err := functions.TposeTrajectory(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TRGeometrySeqSetFromPointer(_r0.Pointer()), nil
}

// ValueAtTimestamptz is MEOS tpose_value_at_timestamptz.
func (x *TPose) ValueAtTimestamptz(t int64, strict bool) (*Pose, bool, error) {
	_found, _value, _err := functions.TposeValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return PoseFromPointer(_value.Pointer()), true, nil
}

// ValueN is MEOS tpose_value_n.
func (x *TPose) ValueN(n int) (*Pose, bool, error) {
	_found, _value, _err := functions.TposeValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return nil, false, _err
	}
	if !_found {
		return nil, false, nil
	}
	return PoseFromPointer(_value.Pointer()), true, nil
}

// Values is MEOS tpose_values.
func (x *TPose) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TposeValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// AtElevation is MEOS tpose_at_elevation.
func (x *TPose) AtElevation(s *Span) (*Temporal, error) {
	_r0, _err := functions.TposeAtElevation(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtGeom is MEOS tpose_at_geom.
func (x *TPose) AtGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TposeAtGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtStbox is MEOS tpose_at_stbox.
func (x *TPose) AtStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TposeAtSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// AtPose is MEOS tpose_at_pose.
func (x *TPose) AtPose(pose *Pose) (*Temporal, error) {
	_r0, _err := functions.TposeAtPose(functions.TemporalFromPointer(x.Pointer()), functions.PoseFromPointer(pose.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusElevation is MEOS tpose_minus_elevation.
func (x *TPose) MinusElevation(s *Span) (*Temporal, error) {
	_r0, _err := functions.TposeMinusElevation(functions.TemporalFromPointer(x.Pointer()), functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusGeom is MEOS tpose_minus_geom.
func (x *TPose) MinusGeom(gs *TRGeometrySeqSet) (*Temporal, error) {
	_r0, _err := functions.TposeMinusGeom(functions.TemporalFromPointer(x.Pointer()), functions.GeomFromPointer(gs.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusPose is MEOS tpose_minus_pose.
func (x *TPose) MinusPose(pose *Pose) (*Temporal, error) {
	_r0, _err := functions.TposeMinusPose(functions.TemporalFromPointer(x.Pointer()), functions.PoseFromPointer(pose.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusStbox is MEOS tpose_minus_stbox.
func (x *TPose) MinusStbox(box *STBox, border_inc bool) (*Temporal, error) {
	_r0, _err := functions.TposeMinusSTBOX(functions.TemporalFromPointer(x.Pointer()), functions.STBoxFromPointer(box.Pointer()), border_inc)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
