package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TPoseSeq struct {
	handle
}

// TPoseSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TPoseSeqFromPointer(p unsafe.Pointer) *TPoseSeq {
	if p == nil {
		return nil
	}
	v := &TPoseSeq{}
	v.ptr = p
	return v
}

// TPoseSeqFromBaseTstzset is MEOS tposeseq_from_base_tstzset.
func TPoseSeqFromBaseTstzset(pose *Pose, s *Set) (*Temporal, error) {
	_r0, _err := functions.TposeseqFromBaseTstzset(functions.PoseFromPointer(pose.Pointer()), functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TPoseSeqFromBaseTstzspan is MEOS tposeseq_from_base_tstzspan.
func TPoseSeqFromBaseTstzspan(pose *Pose, s *Span, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TposeseqFromBaseTstzspan(functions.PoseFromPointer(pose.Pointer()), functions.SpanFromPointer(s.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
