package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TPoseSeqSet struct {
	handle
}

// TPoseSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TPoseSeqSetFromPointer(p unsafe.Pointer) *TPoseSeqSet {
	if p == nil {
		return nil
	}
	v := &TPoseSeqSet{}
	v.ptr = p
	return v
}

// TPoseSeqSetFromBaseTstzspanset is MEOS tposeseqset_from_base_tstzspanset.
func TPoseSeqSetFromBaseTstzspanset(pose *Pose, ss *SpanSet, interp functions.Interpolation) (*Temporal, error) {
	_r0, _err := functions.TposeseqsetFromBaseTstzspanset(functions.PoseFromPointer(pose.Pointer()), functions.SpanSetFromPointer(ss.Pointer()), interp)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
