package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TPoseInst struct {
	handle
}

// TPoseInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TPoseInstFromPointer(p unsafe.Pointer) *TPoseInst {
	if p == nil {
		return nil
	}
	v := &TPoseInst{}
	v.ptr = p
	return v
}

// TPoseInstMake is MEOS tposeinst_make.
func TPoseInstMake(pose *Pose, t int64) (*Temporal, error) {
	_r0, _err := functions.TposeinstMake(functions.PoseFromPointer(pose.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
