package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TRGeometrySeq struct {
	handle
}

// TRGeometrySeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TRGeometrySeqFromPointer(p unsafe.Pointer) *TRGeometrySeq {
	if p == nil {
		return nil
	}
	v := &TRGeometrySeq{}
	v.ptr = p
	return v
}

// TRGeometrySeqMake is MEOS trgeometryseq_make.
func TRGeometrySeqMake(geom *TRGeometrySeqSet, instants unsafe.Pointer, count int, lower_inc bool, upper_inc bool, interp functions.Interpolation, normalize bool) (*Temporal, error) {
	_r0, _err := functions.TrgeometryseqMake(functions.GeomFromPointer(geom.Pointer()), instants, count, lower_inc, upper_inc, interp, normalize)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
