package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TRGeometryInst struct {
	handle
}

// TRGeometryInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TRGeometryInstFromPointer(p unsafe.Pointer) *TRGeometryInst {
	if p == nil {
		return nil
	}
	v := &TRGeometryInst{}
	v.ptr = p
	return v
}

// TRGeometryInstMake is MEOS trgeometryinst_make.
func TRGeometryInstMake(geom *TRGeometrySeqSet, pose *Pose, t int64) (*Temporal, error) {
	_r0, _err := functions.TrgeometryinstMake(functions.GeomFromPointer(geom.Pointer()), functions.PoseFromPointer(pose.Pointer()), t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
