package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TSequence struct {
	Temporal
}

// TSequenceFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TSequenceFromPointer(p unsafe.Pointer) *TSequence {
	if p == nil {
		return nil
	}
	v := &TSequence{}
	v.ptr = p
	return v
}

// TSequenceMake is MEOS tsequence_make.
func TSequenceMake(instants unsafe.Pointer, count int, lower_inc bool, upper_inc bool, interp functions.Interpolation, normalize bool) (*Temporal, error) {
	_r0, _err := functions.TsequenceMake(instants, count, lower_inc, upper_inc, interp, normalize)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
