package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

// TSpatial is temporal types carrying an STBox spatial bounding box.

type TSpatial struct {
	Temporal
}

// TSpatialFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TSpatialFromPointer(p unsafe.Pointer) *TSpatial {
	if p == nil {
		return nil
	}
	v := &TSpatial{}
	v.ptr = p
	return v
}

// Out is MEOS tspatial_out.
func (x *TSpatial) Out(maxdd int) (string, error) {
	_r0, _err := functions.TspatialOut(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsEWKT is MEOS tspatial_as_ewkt.
func (x *TSpatial) AsEWKT(maxdd int) (string, error) {
	_r0, _err := functions.TspatialAsEWKT(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// AsText is MEOS tspatial_as_text.
func (x *TSpatial) AsText(maxdd int) (string, error) {
	_r0, _err := functions.TspatialAsText(functions.TemporalFromPointer(x.Pointer()), maxdd)
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ToStbox is MEOS tspatial_to_stbox.
func (x *TSpatial) ToStbox() (*STBox, error) {
	_r0, _err := functions.TspatialToSTBOX(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return STBoxFromPointer(_r0.Pointer()), nil
}

// SRID is MEOS tspatial_srid.
func (x *TSpatial) SRID() (int32, error) {
	_r0, _err := functions.TspatialSRID(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return 0, _err
	}
	return _r0, nil
}

// SetSRID is MEOS tspatial_set_srid.
func (x *TSpatial) SetSRID(srid int32) (*Temporal, error) {
	_r0, _err := functions.TspatialSetSRID(functions.TemporalFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Transform is MEOS tspatial_transform.
func (x *TSpatial) Transform(srid int32) (*Temporal, error) {
	_r0, _err := functions.TspatialTransform(functions.TemporalFromPointer(x.Pointer()), srid)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TransformPipeline is MEOS tspatial_transform_pipeline.
func (x *TSpatial) TransformPipeline(pipelinestr string, srid int32, is_forward bool) (*Temporal, error) {
	_r0, _err := functions.TspatialTransformPipeline(functions.TemporalFromPointer(x.Pointer()), pipelinestr, srid, is_forward)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
