package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TTextInst struct {
	handle
}

// TTextInstFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TTextInstFromPointer(p unsafe.Pointer) *TTextInst {
	if p == nil {
		return nil
	}
	v := &TTextInst{}
	v.ptr = p
	return v
}

// TTextInstMake is MEOS ttextinst_make.
func TTextInstMake(txt string, t int64) (*Temporal, error) {
	_r0, _err := functions.TtextinstMake(txt, t)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
