package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TTextSeq struct {
	handle
}

// TTextSeqFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TTextSeqFromPointer(p unsafe.Pointer) *TTextSeq {
	if p == nil {
		return nil
	}
	v := &TTextSeq{}
	v.ptr = p
	return v
}

// TTextSeqFromBaseTstzset is MEOS ttextseq_from_base_tstzset.
func TTextSeqFromBaseTstzset(txt string, s *Set) (*Temporal, error) {
	_r0, _err := functions.TtextseqFromBaseTstzset(txt, functions.SetFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TTextSeqFromBaseTstzspan is MEOS ttextseq_from_base_tstzspan.
func TTextSeqFromBaseTstzspan(txt string, s *Span) (*Temporal, error) {
	_r0, _err := functions.TtextseqFromBaseTstzspan(txt, functions.SpanFromPointer(s.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
