package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TText struct {
	TAlpha
}

// TTextFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TTextFromPointer(p unsafe.Pointer) *TText {
	if p == nil {
		return nil
	}
	v := &TText{}
	v.ptr = p
	return v
}

// TTextFromMFJSON is MEOS ttext_from_mfjson.
func TTextFromMFJSON(str string) (*Temporal, error) {
	_r0, _err := functions.TtextFromMFJSON(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// TTextIn is MEOS ttext_in.
func TTextIn(str string) (*Temporal, error) {
	_r0, _err := functions.TtextIn(str)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Out is MEOS ttext_out.
func (x *TText) Out() (string, error) {
	_r0, _err := functions.TtextOut(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// TTextFromBaseTemp is MEOS ttext_from_base_temp.
func TTextFromBaseTemp(txt string, temp *Temporal) (*Temporal, error) {
	_r0, _err := functions.TtextFromBaseTemp(txt, functions.TemporalFromPointer(temp.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// EndValue is MEOS ttext_end_value.
func (x *TText) EndValue() (string, error) {
	_r0, _err := functions.TtextEndValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// MaxValue is MEOS ttext_max_value.
func (x *TText) MaxValue() (string, error) {
	_r0, _err := functions.TtextMaxValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// MinValue is MEOS ttext_min_value.
func (x *TText) MinValue() (string, error) {
	_r0, _err := functions.TtextMinValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// StartValue is MEOS ttext_start_value.
func (x *TText) StartValue() (string, error) {
	_r0, _err := functions.TtextStartValue(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return "", _err
	}
	return _r0, nil
}

// ValueAtTimestamptz is MEOS ttext_value_at_timestamptz.
func (x *TText) ValueAtTimestamptz(t int64, strict bool) (string, bool, error) {
	_found, _value, _err := functions.TtextValueAtTimestamptz(functions.TemporalFromPointer(x.Pointer()), t, strict)
	if _err != nil {
		return "", false, _err
	}
	if !_found {
		return "", false, nil
	}
	return _value, true, nil
}

// ValueN is MEOS ttext_value_n.
func (x *TText) ValueN(n int) (string, bool, error) {
	_found, _value, _err := functions.TtextValueN(functions.TemporalFromPointer(x.Pointer()), n)
	if _err != nil {
		return "", false, _err
	}
	if !_found {
		return "", false, nil
	}
	return _value, true, nil
}

// Values is MEOS ttext_values.
func (x *TText) Values(count unsafe.Pointer) (unsafe.Pointer, error) {
	_r0, _err := functions.TtextValues(functions.TemporalFromPointer(x.Pointer()), count)
	if _err != nil {
		return nil, _err
	}
	return _r0, nil
}

// AtValue is MEOS ttext_at_value.
func (x *TText) AtValue(txt string) (*Temporal, error) {
	_r0, _err := functions.TtextAtValue(functions.TemporalFromPointer(x.Pointer()), txt)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// MinusValue is MEOS ttext_minus_value.
func (x *TText) MinusValue(txt string) (*Temporal, error) {
	_r0, _err := functions.TtextMinusValue(functions.TemporalFromPointer(x.Pointer()), txt)
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Initcap is MEOS ttext_initcap.
func (x *TText) Initcap() (*Temporal, error) {
	_r0, _err := functions.TtextInitcap(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Upper is MEOS ttext_upper.
func (x *TText) Upper() (*Temporal, error) {
	_r0, _err := functions.TtextUpper(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// Lower is MEOS ttext_lower.
func (x *TText) Lower() (*Temporal, error) {
	_r0, _err := functions.TtextLower(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}

// ToTjsonb is MEOS ttext_to_tjsonb.
func (x *TText) ToTjsonb() (*Temporal, error) {
	_r0, _err := functions.TtextToTjsonb(functions.TemporalFromPointer(x.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
