package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"

	"github.com/MobilityDB/GoMEOS/functions"
)

type TTextSeqSet struct {
	handle
}

// TTextSeqSetFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func TTextSeqSetFromPointer(p unsafe.Pointer) *TTextSeqSet {
	if p == nil {
		return nil
	}
	v := &TTextSeqSet{}
	v.ptr = p
	return v
}

// TTextSeqSetFromBaseTstzspanset is MEOS ttextseqset_from_base_tstzspanset.
func TTextSeqSetFromBaseTstzspanset(txt string, ss *SpanSet) (*Temporal, error) {
	_r0, _err := functions.TtextseqsetFromBaseTstzspanset(txt, functions.SpanSetFromPointer(ss.Pointer()))
	if _err != nil {
		return nil, _err
	}
	return TemporalFromPointer(_r0.Pointer()), nil
}
