package types

// Code generated by tools/objectgen.py from meos-idl.json. DO NOT EDIT.

import (
	"unsafe"
)

type Value struct {
	handle
}

// ValueFromPointer wraps a MEOS pointer, answering nil for nil so an
// absent MEOS result stays absent rather than becoming a live handle.
func ValueFromPointer(p unsafe.Pointer) *Value {
	if p == nil {
		return nil
	}
	v := &Value{}
	v.ptr = p
	return v
}
